In [1]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
import pandas as pd
spark = SparkSession.builder \
    .appName('Read CSV File into DataFrame') \
    .config('spark.executor.memory', '10g') \
    .config('spark.driver.memory', '10g') \
    .getOrCreate()
# spark = SparkSession.builder.appName('Read CSV File into DataFrame').getOrCreate()
from pyspark.sql.functions import col

# Load the data into a DataFrame
df_spark = spark.read.csv("/home/nirmala/Documents/precog_requirement_task/acts_sections.csv", header=True)

# Remove the 'act' from the DataFrame
df_spark = df_spark.drop(col("act"))

# Remove the 'section' from the DataFrame
df_spark = df_spark.drop(col("section"))

# Remove the 'bailable_ipc' from the DataFrame
df_spark = df_spark.drop(col("bailable_ipc"))

# Remove the 'number_sections_ipc' from the DataFrame
df_spark = df_spark.drop(col("number_sections_ipc"))
# Write the resulting DataFrame to a CSV file


df1=spark.read.csv("/home/nirmala/Documents/precog_requirement_task/cases/cases/cases_2012.csv" ,header=True)
dp=df1
# df_merged = df.join(df1, on=["ddl_case_id"], how="left").filter(col("ddl_case_id") == col("ddl_case_id"))
df_merged=df_spark.join(df1,
               df_spark.ddl_case_id == df1.ddl_case_id, 
               "right")

# df_merged.count()
# del df_spark
# df=pd.read_csv('/home/nirmala/Documents/precog_requirement_task/cases/cases/cases_2012.csv')
# df_merged.write.csv("2010.csv", mode="overwrite", header=True)

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

23/01/09 22:47:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [2]:
# df_pend=dp
# df_pend = df_pend.drop(col("dist_code"))
# df_pend = df_pend.drop(col("ddl_case_id"))
# df_pend = df_pend.drop(col("court_no"))
# df_pend = df_pend.drop(col("cino"))
# df_pend = df_pend.drop(col("judge_position"))
# df_pend = df_pend.drop(col("female_defendant"))
# df_pend = df_pend.drop(col("female_petitioner"))
# df_pend = df_pend.drop(col("female_adv_def"))
# df_pend = df_pend.drop(col("female_adv_pet"))
# df_pend = df_pend.drop(col("type_name"))
# df_pend = df_pend.drop(col("purpose_name"))
# df_pend = df_pend.drop(col("disp_name"))
# df_pend = df_pend.drop(col("date_last_list"))
# df_pend = df_pend.drop(col("date_first_list"))

In [3]:
del dp

In [4]:
# df = df_pend.toPandas()

In [5]:
# del df_pend

In [6]:
# df['date_of_filing'] = pd.to_datetime(df['date_of_filing'], format='%Y-%m-%d',errors = 'coerce') 
# df['date_of_decision'] = pd.to_datetime(df['date_of_decision'], format='%Y-%m-%d',errors = 'coerce') 
# df['date_next_list'] = pd.to_datetime(df['date_next_list'], format='%Y-%m-%d',errors = 'coerce') 
# # df['file_end'] =(df['date_next_list']-df['date_of_filing']).dt.year

In [7]:
# df['closing'] = df['date_next_list'].dt.year
# df['filing'] = df['date_of_filing'].dt.year
# df=df.drop(columns=['date_of_filing','date_of_decision','date_next_list'])

In [8]:
# df['closing']=df['closing'].fillna('1900')
# df['closing']=df['closing'].astype(int)
# df['filing']=df['filing'].astype(int)

In [9]:
# df = df[~df['closing'].isin([2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022])]
# df['pending_years']=df['closing']-df['filing']
# df=df.drop(columns=['filing','closing'])
# df=df.reset_index()
# df=df.drop(columns=['index'])

In [10]:
# df['state_code'].replace(to_replace='01', value="Maharashtra",inplace=True)
# df['state_code'].replace(to_replace='02' ,value="Andhra Pradesh",inplace=True)
# df['state_code'].replace(to_replace='03' ,value="Karnataka",inplace=True)
# df['state_code'].replace(to_replace='04', value="Kerala",inplace=True)
# df['state_code'].replace(to_replace='05' ,value="Himachal Pradesh",inplace=True)
# df['state_code'].replace(to_replace='06', value="Assam",inplace=True)
# df['state_code'].replace(to_replace='07', value="Jharkhand",inplace=True)
# df['state_code'].replace(to_replace='08' ,value="Bihar",inplace=True)
# df['state_code'].replace(to_replace='09' ,value="Rajasthan",inplace=True)
# df['state_code'].replace(to_replace='10' ,value="Tamilnadu",inplace=True)
# df['state_code'].replace(to_replace='11',value="Orissa",inplace=True)
# df['state_code'].replace(to_replace='12' ,value="Jammu and kashmir",inplace=True)
# df['state_code'].replace(to_replace='13' ,value="Uttar pradesh",inplace=True)
# df['state_code'].replace(to_replace='14' ,value="Haryana",inplace=True)
# df['state_code'].replace(to_replace='15' ,value="Uttarakhand",inplace=True)
# df['state_code'].replace(to_replace='16' ,value="West Bengal",inplace=True)
# df['state_code'].replace(to_replace='17' ,value="Gujarath",inplace=True)
# df['state_code'].replace(to_replace='18' ,value="Chattisgarh",inplace=True)
# df['state_code'].replace(to_replace='19' ,value="Mizoram",inplace=True)
# df['state_code'].replace(to_replace='20' ,value="Tripura",inplace=True)
# df['state_code'].replace(to_replace='21' ,value="Meghalaya",inplace=True)
# df['state_code'].replace(to_replace='22' ,value="Punjab",inplace=True)
# df['state_code'].replace(to_replace='23' ,value="Madhya Pradesh",inplace=True)
# df['state_code'].replace(to_replace='24' , value="Sikkim",inplace=True)
# df['state_code'].replace(to_replace='25' ,value="Manipur",inplace=True)
# df['state_code'].replace(to_replace='26' ,value="Delhi",inplace=True)
# df['state_code'].replace(to_replace='27' ,value="Chandigarh",inplace=True)
# df['state_code'].replace(to_replace='29' ,value="Telangana",inplace=True)
# df['state_code'].replace(to_replace='30' ,value="Goa",inplace=True)
# df['state_code'].replace(to_replace='31' ,value="Diu and daman",inplace=True)
# df['state_code'].replace(to_replace='32',value="DNH at silvasa",inplace=True)
# df['state_code'].replace(to_replace='33' ,value="Ladakh",inplace=True)

In [11]:
# df_pending = df["state_code"].value_counts().reset_index()
# df_pending['state_code']=df_pending['state_code'].sort_values()
# df_pending.rename(columns={"index": "state", "state_code": "pendingcases_count"}, inplace=True)
# new_rows_pending = pd.DataFrame({'state' : ['Diu and daman','Ladakh','DNH at silvasa','Manipur','Meghalaya','Mizoram','Sikkim'], 'pendingcases_count' : [0,0,0,0,0,0,0]})
# df_pending= pd.concat([new_rows_pending, df_pending], ignore_index=True)
# df_pending['pending_casesperlakh']=df_pending['pendingcases_count']/100000
# df_pending.insert(3, 'Year', 2012)

In [12]:
# del df

In [13]:

df_merged = df_merged.drop(col("dist_code"))

# Remove the 'section' from the DataFrame
df_merged = df_merged.drop(col("cino"))

# Remove the 'bailable_ipc' from the DataFrame
df_merged = df_merged.drop(col("court_no"))

# Remove the 'number_sections_ipc' from the DataFrame
df_merged = df_merged.drop(col("judge_position"))

df_merged = df_merged.drop(col("type_name"))

df_merged = df_merged.drop(col("purpose_name"))

df_merged = df_merged.drop(col("date_last_list"))

df_merged = df_merged.drop(col("female_adv_def"))

df_merged = df_merged.drop(col("female_petitioner"))

df_merged = df_merged.drop(col("female_adv_pet"))

df_merged = df_merged.drop(col("female_defendant"))

In [14]:

df_pandas = df_merged.toPandas()
df_pandas_copy=df_pandas

In [15]:

del df_merged
del df_spark

In [16]:
df_pandas=df_pandas.drop(df_pandas.columns[0], axis=1)

In [17]:
df_2012=df_pandas
del df_pandas

# df_2012=df_2012.drop(columns=["ddl_case_id","cino"])
df_2012['state_code'].replace(to_replace='01', value="Maharashtra",inplace=True)
df_2012['state_code'].replace(to_replace='02' ,value="Andhra Pradesh",inplace=True)
df_2012['state_code'].replace(to_replace='03' ,value="Karnataka",inplace=True)
df_2012['state_code'].replace(to_replace='04', value="Kerala",inplace=True)
df_2012['state_code'].replace(to_replace='05' ,value="Himachal Pradesh",inplace=True)
df_2012['state_code'].replace(to_replace='06', value="Assam",inplace=True)
df_2012['state_code'].replace(to_replace='07', value="Jharkhand",inplace=True)
df_2012['state_code'].replace(to_replace='08' ,value="Bihar",inplace=True)
df_2012['state_code'].replace(to_replace='09' ,value="Rajasthan",inplace=True)
df_2012['state_code'].replace(to_replace='10' ,value="Tamilnadu",inplace=True)
df_2012['state_code'].replace(to_replace='11',value="Orissa",inplace=True)
df_2012['state_code'].replace(to_replace='12' ,value="Jammu and kashmir",inplace=True)
df_2012['state_code'].replace(to_replace='13' ,value="Uttar pradesh",inplace=True)
df_2012['state_code'].replace(to_replace='14' ,value="Haryana",inplace=True)
df_2012['state_code'].replace(to_replace='15' ,value="Uttarakhand",inplace=True)
df_2012['state_code'].replace(to_replace='16' ,value="West Bengal",inplace=True)
df_2012['state_code'].replace(to_replace='17' ,value="Gujarath",inplace=True)
df_2012['state_code'].replace(to_replace='18' ,value="Chattisgarh",inplace=True)
df_2012['state_code'].replace(to_replace='19' ,value="Mizoram",inplace=True)
df_2012['state_code'].replace(to_replace='20' ,value="Tripura",inplace=True)
df_2012['state_code'].replace(to_replace='21' ,value="Meghalaya",inplace=True)
df_2012['state_code'].replace(to_replace='22' ,value="Punjab",inplace=True)
df_2012['state_code'].replace(to_replace='23' ,value="Madhya Pradesh",inplace=True)
df_2012['state_code'].replace(to_replace='24' , value="Sikkim",inplace=True)
df_2012['state_code'].replace(to_replace='25' ,value="Manipur",inplace=True)
df_2012['state_code'].replace(to_replace='26' ,value="Delhi",inplace=True)
df_2012['state_code'].replace(to_replace='27' ,value="Chandigarh",inplace=True)
df_2012['state_code'].replace(to_replace='29' ,value="Telangana",inplace=True)
df_2012['state_code'].replace(to_replace='30' ,value="Goa",inplace=True)
df_2012['state_code'].replace(to_replace='31' ,value="Diu and daman",inplace=True)
df_2012['state_code'].replace(to_replace='32',value="DNH at silvasa",inplace=True)
df_2012['state_code'].replace(to_replace='33' ,value="Ladakh",inplace=True)
def create_new_column(row):
    if pd.isnull(row['date_next_list']):
        return 1
    else:
        return 0
df_2012['pending'] = df_2012.apply(create_new_column, axis=1)

In [18]:
df_2012['filing'] = pd.to_datetime(df_2012['date_of_filing'], format='%Y-%m-%d',errors = 'coerce') 
df_2012['first_list'] = pd.to_datetime(df_2012['date_first_list'], format='%Y-%m-%d',errors = 'coerce') 
df_2012['decision'] = pd.to_datetime(df_2012['date_of_decision'], format='%Y-%m-%d',errors = 'coerce') 
df_2012['last_list'] = pd.to_datetime(df_2012['date_next_list'], format='%Y-%m-%d',errors = 'coerce') 
df_2012['date_next_list'] = pd.to_datetime(df_2012['date_next_list'], format='%Y-%m-%d',errors = 'coerce') 
df_2012['closing'] = df_2012['date_next_list'].dt.year
df_2012['closing']=df_2012['closing'].fillna('1900')
df_2012=df_2012.drop(columns=['date_of_filing','date_of_decision','date_first_list','date_next_list'])
df_2012['file_reachcourt'] =(df_2012['first_list']-df_2012['filing']).dt.days
df_2012['file_end'] =(df_2012['last_list']-df_2012['filing']).dt.days
df_2012['decision_end'] =(df_2012['last_list']-df_2012['decision']).dt.days

In [19]:
df_2012=df_2012.drop(columns=['first_list','decision','last_list'])
def replace_negatives(x):
    if x < 0:
        return -1
    return x
df_2012['file_reachcourt']=df_2012['file_reachcourt'].apply(replace_negatives)
df_2012['file_end']=df_2012['file_end'].apply(replace_negatives)
df_2012['decision_end']=df_2012['decision_end'].apply(replace_negatives)

In [20]:
df_2012['criminal'].unique()
df_2012['criminal'].replace(to_replace='0',value='criminal',inplace=True)
df_2012['criminal'].replace(to_replace='1',value='Non-criminal',inplace=True)

In [21]:
import numpy as np
df_2012['file_reachcourt'] = pd.to_numeric(df_2012['file_reachcourt'], errors='coerce')
# Fill the missing and infinite values with -1
df_2012['file_reachcourt'] = df_2012['file_reachcourt'].fillna(-1).replace([np.inf, -np.inf], -1)
# Convert the 'file_reachcourt' column to integers
df_2012['file_reachcourt'] = df_2012['file_reachcourt'].astype(int)
df_2012['file_end'] = pd.to_numeric(df_2012['file_end'], errors='coerce')
# Fill the missing and infinite values with -1
df_2012['file_end'] = df_2012['file_end'].fillna(-1).replace([np.inf, -np.inf], -1)

In [22]:

# Convert the 'file_end ' column to integers
df_2012['file_end'] = df_2012['file_end'].astype(int)

df_2012['decision_end'] = pd.to_numeric(df_2012['decision_end'], errors='coerce')

# Fill the missing and infinite values with -1
df_2012['decision_end'] = df_2012['decision_end'].fillna(-1).replace([np.inf, -np.inf], -1)

# Convert the 'decision_end' column to integers
df_2012['decision_end'] = df_2012['decision_end'].astype(int)

In [23]:

# df_2012['criminal'] = df_2012['criminal'].fillna(-1)
# del temp
# del non_criminal_count_2012
#criminal count
temp=df_2012
temp2=df_2012
temp_noncriminal=temp2.drop(temp2[temp2['criminal']=='None'].index)
temp_noncriminal=temp_noncriminal.drop(temp_noncriminal[temp_noncriminal['criminal']=='criminal'].index)
temp_criminal= temp.drop(temp[temp['criminal']=='None'].index)  
temp_criminal= temp_criminal.drop(temp_criminal[temp_criminal['criminal']=='Non-criminal'].index)

# Criminal count

In [24]:
criminal_count_2012 = temp_criminal["state_code"].value_counts().reset_index()
# Rename the "index" and "Year" columns
criminal_count_2012['state_code']=criminal_count_2012['state_code'].sort_values()
criminal_count_2012.rename(columns={"index": "state", "state_code": "criminal_count"}, inplace=True)
criminal_count_2012['state']=criminal_count_2012['state'].sort_values()
criminal_count_2012=criminal_count_2012.sort_values(by='state')
criminal_count_2012.insert(2, 'Year', 2012)
criminal_count_2012=criminal_count_2012.reset_index()
criminal_count_2012=criminal_count_2012.drop(columns=['index'])
del temp_criminal
criminal_count_2012['criminal_perlakh']=criminal_count_2012['criminal_count']/100000
non_criminal_count_2012 = temp_noncriminal["state_code"].value_counts().reset_index()
# Rename the "index" and "Year" columns
non_criminal_count_2012['state_code']=non_criminal_count_2012['state_code'].sort_values()
non_criminal_count_2012.rename(columns={"index": "state", "state_code": "noncriminal_count"}, inplace=True)
non_criminal_count_2012['state']=non_criminal_count_2012['state'].sort_values()
non_criminal_count_2012=non_criminal_count_2012.sort_values(by='state')
# non_criminal_count_2012.insert(2, 'Year', 2012)
non_criminal_count_2012=non_criminal_count_2012.reset_index()
non_criminal_count_2012=non_criminal_count_2012.drop(columns=['index'])
df_criminal_not=pd.merge(criminal_count_2012,non_criminal_count_2012,on='state')
df_criminal_not['noncriminal_perlakh']=df_criminal_not['noncriminal_count']/100000

# Pending Cases in 2010

In [25]:
# del pending_Cases

In [26]:
# df['date_of_filing'] = pd.to_datetime(df['date_of_filing'], format='%Y-%m-%d',errors = 'coerce') 
# df['date_of_decision'] = pd.to_datetime(df['date_of_decision'], format='%Y-%m-%d',errors = 'coerce') 
# df['date_next_list'] = pd.to_datetime(df['date_next_list'], format='%Y-%m-%d',errors = 'coerce') 
# # df['file_end'] =(df['date_next_list']-df['date_of_filing']).dt.year

In [27]:

# df['closing'] = df['date_next_list'].dt.year
# df['filing'] = df['date_of_filing'].dt.year
# df=df.drop(columns=['date_of_filing','date_of_decision','date_next_list'])

In [28]:
# df['closing']=df['closing'].fillna('1900')
# df['closing']=df['closing'].astype(int)
# df['filing']=df['filing'].astype(int)

In [29]:
# df = df[~df['closing'].isin([2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022])]
# df['pending_years']=df['closing']-df['filing']
# df=df.drop(columns=['filing','closing'])
# df=df.reset_index()
# df=df.drop(columns=['index'])

In [30]:
# df['state_code'].replace(to_replace='01', value="Maharashtra",inplace=True)
# df['state_code'].replace(to_replace='02' ,value="Andhra Pradesh",inplace=True)
# df['state_code'].replace(to_replace='03' ,value="Karnataka",inplace=True)
# df['state_code'].replace(to_replace='04', value="Kerala",inplace=True)
# df['state_code'].replace(to_replace='05' ,value="Himachal Pradesh",inplace=True)
# df['state_code'].replace(to_replace='06', value="Assam",inplace=True)
# df['state_code'].replace(to_replace='07', value="Jharkhand",inplace=True)
# df['state_code'].replace(to_replace='08' ,value="Bihar",inplace=True)
# df['state_code'].replace(to_replace='09' ,value="Rajasthan",inplace=True)
# df['state_code'].replace(to_replace='10' ,value="Tamilnadu",inplace=True)
# df['state_code'].replace(to_replace='11',value="Orissa",inplace=True)
# df['state_code'].replace(to_replace='12' ,value="Jammu and kashmir",inplace=True)
# df['state_code'].replace(to_replace='13' ,value="Uttar pradesh",inplace=True)
# df['state_code'].replace(to_replace='14' ,value="Haryana",inplace=True)
# df['state_code'].replace(to_replace='15' ,value="Uttarakhand",inplace=True)
# df['state_code'].replace(to_replace='16' ,value="West Bengal",inplace=True)
# df['state_code'].replace(to_replace='17' ,value="Gujarath",inplace=True)
# df['state_code'].replace(to_replace='18' ,value="Chattisgarh",inplace=True)
# df['state_code'].replace(to_replace='19' ,value="Mizoram",inplace=True)
# df['state_code'].replace(to_replace='20' ,value="Tripura",inplace=True)
# df['state_code'].replace(to_replace='21' ,value="Meghalaya",inplace=True)
# df['state_code'].replace(to_replace='22' ,value="Punjab",inplace=True)
# df['state_code'].replace(to_replace='23' ,value="Madhya Pradesh",inplace=True)
# df['state_code'].replace(to_replace='24' , value="Sikkim",inplace=True)
# df['state_code'].replace(to_replace='25' ,value="Manipur",inplace=True)
# df['state_code'].replace(to_replace='26' ,value="Delhi",inplace=True)
# df['state_code'].replace(to_replace='27' ,value="Chandigarh",inplace=True)
# df['state_code'].replace(to_replace='29' ,value="Telangana",inplace=True)
# df['state_code'].replace(to_replace='30' ,value="Goa",inplace=True)
# df['state_code'].replace(to_replace='31' ,value="Diu and daman",inplace=True)
# df['state_code'].replace(to_replace='32',value="DNH at silvasa",inplace=True)
# df['state_code'].replace(to_replace='33' ,value="Ladakh",inplace=True)

In [31]:
# df_pending = df["state_code"].value_counts().reset_index()
# df_pending['state_code']=df_pending['state_code'].sort_values()
# df_pending.rename(columns={"index": "state", "state_code": "pendingcases_count"}, inplace=True)
# new_rows_pending = pd.DataFrame({'state' : ['Diu and daman','Ladakh','DNH at silvasa','Manipur','Meghalaya','Mizoram','Sikkim'], 'pendingcases_count' : [0,0,0,0,0,0,0]})
# pending_Cases= pd.concat([new_rows_pending, pending_Cases], ignore_index=True)
# df_pending['pending_casesperlakh']=df_pending['pendingcases_count']/100000
# df_pending.insert(3, 'Year', 2012)

# Average Time to reach court after filing per 1 lakh cases

In [32]:
# Average Time to reach court after filing per 1 lakh cases
del temp
temp=df_2012
avg_file_court=temp.drop(temp[temp['file_reachcourt'] < 0].index)
# del avg_file_court
# filing_reach = df["file_reachcourt"].value_counts().reset_index()
avg_file_court = avg_file_court.groupby('state_code')
# df_mean = filing_reach['file_reachcourt'].mean()
def avg_days(group,column):
    return group[column].mean() / group[column].count() * 100000
df_avg_days = avg_file_court.apply(avg_days,"file_reachcourt")
# # Rename the "index" and "Year" columns
# year_counts_end.rename(columns={"index": "year", "year2": "count_of_end"}, inplace=True)
# year_counts_end
del avg_file_court
file_court_avg=df_avg_days.to_frame().reset_index()
# pandas_s.info()
file_court_avg.rename(columns={"state_code": "state", 0: "avg_filecourt_per1lakhcases"}, inplace=True)
# new_rows_file_court_avg = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'avg_filecourt_per1lakhcases' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})
# file_court_avg= pd.concat([new_rows_file_court_avg, file_court_avg], ignore_index=True)
del df_avg_days
file_court_avg=file_court_avg.sort_values(by='state')
file_court_avg=file_court_avg.reset_index()
file_court_avg=file_court_avg.drop(columns=['index'])  
file_court_avg.insert(2, 'Year', 2012)
# file_court_avg=file_court_avg.drop(columns=['Year'])  
file_court_avg['avg_filecourt_per1lakhcases']=file_court_avg['avg_filecourt_per1lakhcases'].astype(int)

# Average Time to End case after filing per 1 lakh cases in 2010

In [33]:
temp=df_2012
avg_file_end=temp.drop(temp[temp['file_end'] < 0].index)
# del avg_file_end
# filing_reach = df["file_end"].value_counts().reset_index()
avg_file_end = avg_file_end.groupby('state_code')
# df_mean = filing_reach['file_end'].mean()
def avg_days(group,column):
    return group[column].mean() / group[column].count() * 100000

df_avg_days = avg_file_end.apply(avg_days,"file_end")
# # Rename the "index" and "Year" columns
# year_counts_end.rename(columns={"index": "year", "year2": "count_of_end"}, inplace=True)
# year_counts_end
file_End_avg=df_avg_days.to_frame().reset_index()
# pandas_s.info()
file_End_avg.rename(columns={"state_code": "state", 0: "avg_fileend_per1lakhcases"}, inplace=True)
# new_rows_file_End_avg = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'avg_fileend_per1lakhcases' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})
# file_End_avg= pd.concat([new_rows_file_End_avg, file_End_avg], ignore_index=True)
# file_End_avg
file_End_avg=file_End_avg.sort_values(by='state')
file_End_avg=file_End_avg.reset_index()
file_End_avg=file_End_avg.drop(columns=['index'])  
file_End_avg.insert(2, 'Year', 2012)
file_End_avg['avg_fileend_per1lakhcases']=file_End_avg['avg_fileend_per1lakhcases'].astype(int)
del avg_file_end
del df_avg_days
file_End_avg['avg_fileend_per1lakhcases']=file_End_avg['avg_fileend_per1lakhcases'].astype(int)

# Average Time to End case after decision per 1 lakh cases in 2012

In [34]:
del temp
temp=df_2012
avg_decision_end=temp.drop(temp[temp['decision_end'] < 0].index)
# del avg_decision_end
# filing_reach = df["decision_end"].value_counts().reset_index()
avg_decision_end = avg_decision_end.groupby('state_code')
# df_mean = filing_reach['decision_end'].mean()
def avg_days(group,column):
    return group[column].mean() / group[column].count() * 100000
df_avg_days = avg_decision_end.apply(avg_days,"decision_end")
# # Rename the "index" and "Year" columns
# year_counts_end.rename(columns={"index": "year", "year2": "count_of_end"}, inplace=True)
# year_counts_end
decision_end_avg=df_avg_days.to_frame().reset_index()
# pandas_s.info()
decision_end_avg.rename(columns={"state_code": "state", 0: "avg_decision_end_per1lakhcases"}, inplace=True)
# new_rows_decision_end_avg = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'avg_decision_end_per1lakhcases' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})
# decision_end_avg= pd.concat([new_rows_decision_end_avg, decision_end_avg], ignore_index=True)
# decision_end_avg
decision_end_avg=decision_end_avg.sort_values(by='state')
decision_end_avg=decision_end_avg.reset_index()
decision_end_avg=decision_end_avg.drop(columns=['index'])  
decision_end_avg.insert(2, 'Year', 2012)
decision_end_avg['avg_decision_end_per1lakhcases']=decision_end_avg['avg_decision_end_per1lakhcases'].astype(int)
del df_avg_days
del avg_decision_end

# Withdrawal

In [35]:
del temp
temp=df_2012
withdrawal=temp[temp['disp_name'] == '51']
# del avg_decision_end
# withdrawal
withdrawal = withdrawal["state_code"].value_counts().reset_index()
# Rename the "index" and "Year" columns
withdrawal['state_code']=withdrawal['state_code'].sort_values()
withdrawal.rename(columns={"index": "state", "state_code": "withdrawal_count"}, inplace=True)
# new_rows_withdrawal = pd.DataFrame({'state' : [ 'Ladakh'], 'withdrawal_count' : [ 0 ]})
# withdrawal
# withdrawal= pd.concat([new_rows_withdrawal, withdrawal], ignore_index=True)
# withdrawal
withdrawal=withdrawal.reset_index()
withdrawal=withdrawal.drop(columns=['index'])  
withdrawal.insert(2, 'Year', 2012)

# Prison

In [37]:
# del prison

In [38]:
del temp
temp=df_2012
prison=temp[temp['disp_name'] == '38']
prison = prison["state_code"].value_counts().reset_index()
# Rename the "index" and "Year" columns
prison['state_code']=prison['state_code'].sort_values()
prison.rename(columns={"index": "state", "state_code": "prison_count"}, inplace=True)
new_rows_prison = pd.DataFrame({'state' : ['Andhra Pradesh','Karnataka', 'Kerala', 'Himachal Pradesh', 'Tamilnadu','Jammu and kashmir','Uttar pradesh','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Madhya Pradesh','Sikkim','Manipur','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh','Delhi','Orissa'], 'prison_count' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})
prison= pd.concat([new_rows_prison, prison], ignore_index=True)
prison=prison.sort_values(by='state')
prison=prison.reset_index()
prison=prison.drop(columns=['index'])  
prison.insert(2, 'Year', 2012)

# Dismissed cases

In [39]:
del dismissed

NameError: name 'dismissed' is not defined

In [40]:
del temp
temp=df_2012
dismissed=temp[temp['disp_name'] == '22']
# del avg_decision_end
dismissed = dismissed["state_code"].value_counts().reset_index()
dismissed['state_code']=dismissed['state_code'].sort_values()
dismissed.rename(columns={"index": "state", "state_code": "dismissed_count"}, inplace=True)
new_rows_dismissed = pd.DataFrame({'state' : [ 'Ladakh'], 'dismissed_count' : [ 0 ]})
dismissed= pd.concat([new_rows_dismissed, dismissed], ignore_index=True)
dismissed=dismissed.sort_values(by='state')
dismissed=dismissed.reset_index()
dismissed=dismissed.drop(columns=['index'])  
dismissed.insert(2, 'Year', 2012)

# Merging

In [41]:
df_merged=pd.merge(dismissed,prison,on='state')
df_merged=pd.merge(df_merged,withdrawal,on='state')
df_merged=pd.merge(df_merged,decision_end_avg,on='state')
df_merged=pd.merge(df_merged,file_End_avg,on='state')
df_merged=pd.merge(df_merged,file_court_avg,on='state')
df_merged=pd.merge(df_merged,df_criminal_not,on='state')
# df_merged=df_merged.drop(columns='Year_x')
# # df_merged=df_merged.drop(df_merged.columns[[3, 6, 9,13]],axis = 1)
# df_merged['year']=[2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012]
# df_merged=df_merged.reindex(columns=['year','state','dismissed_count','prison_count','withdrawal_count','avg_decision_end_per1lakhcases','avg_fileend_per1lakhcases','avg_filecourt_per1lakhcases','criminal_count','criminal_count','criminal_perlakh','noncriminal_count','noncriminal_perlakh'])
# df_merged.info()
# df_merged.to_csv('2012_filtered.csv', index=False)
df_merged

/tmp/ipykernel_5389/3054074867.py:3: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Year_x'} in the result is deprecated and will raise a MergeError in a future version.
  df_merged=pd.merge(df_merged,decision_end_avg,on='state')
/tmp/ipykernel_5389/3054074867.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Year_x'} in the result is deprecated and will raise a MergeError in a future version.
  df_merged=pd.merge(df_merged,file_court_avg,on='state')

,state,dismissed_count,Year_x,prison_count,Year_y,withdrawal_count,Year_x,avg_decision_end_per1lakhcases,Year_y,avg_fileend_per1lakhcases,Year_x,avg_filecourt_per1lakhcases,Year_y,criminal_count,Year,criminal_perlakh,noncriminal_count,noncriminal_perlakh
0,Andhra Pradesh,40361,2012,0,2012,2068,2012,0,2012,503,2012,114,2012,123052,2012,1.23052,72407,0.72407
1,Assam,12621,2012,422,2012,1183,2012,2,2012,953,2012,329,2012,56425,2012,0.56425,77753,0.77753
2,Bihar,22569,2012,1,2012,1413,2012,8,2012,889,2012,419,2012,97259,2012,0.97259,188089,1.88089
3,Chandigarh,3642,2012,0,2012,3959,2012,75,2012,3146,2012,579,2012,18866,2012,0.18866,16193,0.16193
4,Chattisgarh,9624,2012,0,2012,1279,2012,2,2012,1474,2012,382,2012,45705,2012,0.45705,42401,0.42401
5,DNH at silvasa,66,2012,0,2012,66,2012,1,2012,108045,2012,5640,2012,456,2012,0.00456,599,0.00599
6,Delhi,18030,2012,0,2012,18388,2012,7,2012,749,2012,85,2012,99364,2012,0.99364,75430,0.75430
7,Diu and daman,99,2012,0,2012,96,2012,0,2012,30886,2012,3536,2012,1021,2012,0.01021,342,0.00342
8,Goa,26,2012,0,2012,88,2012,83,2012,2403,2012,502,2012,24438,2012,0.24438,20889,0.20889
9,Gujarath,30255,2012,0,2012,35241,2012,0,2012,202,2012,68,2012,330509,2012,3.30509,201861,2.01861
10,Haryana,47971,2012,43,2012,36593,2012,2,2012,317,2012,77,2012,206020,2012,2.06020,189605,1.89605
11,Himachal Pradesh,10093,2012,0,2012,6728,2012,4,2012,1480,2012,292,2012,60469,2012,0.60469,59573,0.59573
12,Jammu and kashmir,3120,2012,0,2012,727,2012,8,2012,3832,2012,1866,2012,28728,2012,0.28728,21278,0.21278
13,Jharkhand,10552,2012,9,2012,1650,2012,3,2012,1634,2012,548,2012,51391,2012,0.51391,66915,0.66915
14,Karnataka,103497,2012,0,2012,6394,2012,0,2012,94,2012,19,2012,646999,2012,6.46999,479755,4.79755
15,Kerala,44570,2012,0,2012,2705,2012,1,2012,243,2012,72,2012,241531,2012,2.41531,155751,1.55751
16,Ladakh,0,2012,0,2012,1,2012,0,2012,18923611,2012,15095833,2012,11,2012,0.00011,5,0.00005
17,Madhya Pradesh,47558,2012,0,2012,10083,2012,5,2012,225,2012,71,2012,319767,2012,3.19767,310358,3.10358
18,Maharashtra,70791,2012,1,2012,27300,2012,0,2012,95,2012,7,2012,681254,2012,6.81254,487126,4.87126
19,Manipur,513,2012,0,2012,40,2012,74,2012,34817,2012,10691,2012,2279,2012,0.02279,1950,0.01950
20,Meghalaya,235,2012,0,2012,103,2012,13,2012,29777,2012,3372,2012,2563,2012,0.02563,2590,0.02590
21,Mizoram,53,2012,0,2012,27,2012,0,2012,11713,2012,6588,2012,1757,2012,0.01757,1728,0.01728
22,Orissa,8236,2012,0,2012,13169,2012,12,2012,1363,2012,533,2012,104124,2012,1.04124,101776,1.01776
23,Punjab,70008,2012,80,2012,41058,2012,1,2012,268,2012,48,2012,236295,2012,2.36295,218127,2.18127
24,Rajasthan,19903,2012,14,2012,12195,2012,2,2012,363,2012,93,2012,303470,2012,3.03470,302041,3.02041
25,Sikkim,26,2012,0,2012,57,2012,121,2012,44366,2012,15857,2012,734,2012,0.00734,779,0.00779
26,Tamilnadu,79295,2012,0,2012,2390,2012,0,2012,407,2012,109,2012,250103,2012,2.50103,206983,2.06983
27,Telangana,28547,2012,0,2012,1127,2012,0,2012,675,2012,178,2012,83434,2012,0.83434,74818,0.74818
28,Tripura,735,2012,0,2012,87,2012,5,2012,7009,2012,1667,2012,7681,2012,0.07681,9584,0.09584
29,Uttar pradesh,98376,2012,0,2012,2166,2012,4,2012,142,2012,38,2012,879105,2012,8.79105,854263,8.54263
30,Uttarakhand,16966,2012,0,2012,305,2012,9,2012,1315,2012,505,2012,59919,2012,0.59919,24828,0.24828
31,West Bengal,41395,2012,0,2012,1043,2012,2,2012,643,2012,307,2012,177796,2012,1.77796,179612,1.79612

In [45]:
df_merged['year']=[2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012,2012]
df_merged=df_merged.reindex(columns=['year','state','dismissed_count','prison_count','withdrawal_count','avg_decision_end_per1lakhcases','avg_fileend_per1lakhcases','avg_filecourt_per1lakhcases','criminal_count','criminal_count','criminal_perlakh','noncriminal_count','noncriminal_perlakh'])
df_merged.info()
df_merged.to_csv('2012_filtered.csv', index=False)
df_merged

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32 entries, 0 to 31
Data columns (total 13 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   year                            32 non-null     int64
 1   state                           32 non-null     object
 2   dismissed_count                 32 non-null     int64
 3   prison_count                    32 non-null     int64
 4   withdrawal_count                32 non-null     int64
 5   avg_decision_end_per1lakhcases  32 non-null     int64
 6   avg_fileend_per1lakhcases       32 non-null     int64
 7   avg_filecourt_per1lakhcases     32 non-null     int64
 8   criminal_count                  32 non-null     int64
 9   criminal_count                  32 non-null     int64
 10  criminal_perlakh                32 non-null     float64
 11  noncriminal_count               32 non-null     int64
 12  noncriminal_perlakh             32 non-null     float64
dtypes: float64(2), int64(10), object(1)
memory usage: 3.5+ KB

,year,state,dismissed_count,prison_count,withdrawal_count,avg_decision_end_per1lakhcases,avg_fileend_per1lakhcases,avg_filecourt_per1lakhcases,criminal_count,criminal_count,criminal_perlakh,noncriminal_count,noncriminal_perlakh
0,2012,Andhra Pradesh,40361,0,2068,0,503,114,123052,123052,1.23052,72407,0.72407
1,2012,Assam,12621,422,1183,2,953,329,56425,56425,0.56425,77753,0.77753
2,2012,Bihar,22569,1,1413,8,889,419,97259,97259,0.97259,188089,1.88089
3,2012,Chandigarh,3642,0,3959,75,3146,579,18866,18866,0.18866,16193,0.16193
4,2012,Chattisgarh,9624,0,1279,2,1474,382,45705,45705,0.45705,42401,0.42401
5,2012,DNH at silvasa,66,0,66,1,108045,5640,456,456,0.00456,599,0.00599
6,2012,Delhi,18030,0,18388,7,749,85,99364,99364,0.99364,75430,0.75430
7,2012,Diu and daman,99,0,96,0,30886,3536,1021,1021,0.01021,342,0.00342
8,2012,Goa,26,0,88,83,2403,502,24438,24438,0.24438,20889,0.20889
9,2012,Gujarath,30255,0,35241,0,202,68,330509,330509,3.30509,201861,2.01861
10,2012,Haryana,47971,43,36593,2,317,77,206020,206020,2.06020,189605,1.89605
11,2012,Himachal Pradesh,10093,0,6728,4,1480,292,60469,60469,0.60469,59573,0.59573
12,2012,Jammu and kashmir,3120,0,727,8,3832,1866,28728,28728,0.28728,21278,0.21278
13,2012,Jharkhand,10552,9,1650,3,1634,548,51391,51391,0.51391,66915,0.66915
14,2012,Karnataka,103497,0,6394,0,94,19,646999,646999,6.46999,479755,4.79755
15,2012,Kerala,44570,0,2705,1,243,72,241531,241531,2.41531,155751,1.55751
16,2012,Ladakh,0,0,1,0,18923611,15095833,11,11,0.00011,5,0.00005
17,2012,Madhya Pradesh,47558,0,10083,5,225,71,319767,319767,3.19767,310358,3.10358
18,2012,Maharashtra,70791,1,27300,0,95,7,681254,681254,6.81254,487126,4.87126
19,2012,Manipur,513,0,40,74,34817,10691,2279,2279,0.02279,1950,0.01950
20,2012,Meghalaya,235,0,103,13,29777,3372,2563,2563,0.02563,2590,0.02590
21,2012,Mizoram,53,0,27,0,11713,6588,1757,1757,0.01757,1728,0.01728
22,2012,Orissa,8236,0,13169,12,1363,533,104124,104124,1.04124,101776,1.01776
23,2012,Punjab,70008,80,41058,1,268,48,236295,236295,2.36295,218127,2.18127
24,2012,Rajasthan,19903,14,12195,2,363,93,303470,303470,3.03470,302041,3.02041
25,2012,Sikkim,26,0,57,121,44366,15857,734,734,0.00734,779,0.00779
26,2012,Tamilnadu,79295,0,2390,0,407,109,250103,250103,2.50103,206983,2.06983
27,2012,Telangana,28547,0,1127,0,675,178,83434,83434,0.83434,74818,0.74818
28,2012,Tripura,735,0,87,5,7009,1667,7681,7681,0.07681,9584,0.09584
29,2012,Uttar pradesh,98376,0,2166,4,142,38,879105,879105,8.79105,854263,8.54263
30,2012,Uttarakhand,16966,0,305,9,1315,505,59919,59919,0.59919,24828,0.24828
31,2012,West Bengal,41395,0,1043,2,643,307,177796,177796,1.77796,179612,1.79612