In [2]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
import pandas as pd
spark = SparkSession.builder \
    .appName('Read CSV File into DataFrame') \
    .config('spark.executor.memory', '14g')\
    .config('spark.driver.memory', '50g')\
    .getOrCreate()
from pyspark.sql.functions import col
df_spark = spark.read.csv("/home/nirmala/Documents/precog_requirement_task/acts_sections.csv", header=True)
df_spark = df_spark.drop(col("act"))
df_spark = df_spark.drop(col("section"))
df_spark = df_spark.drop(col("bailable_ipc"))
df_spark = df_spark.drop(col("number_sections_ipc"))

In [3]:
df1=spark.read.csv("/home/nirmala/Documents/precog_requirement_task/cases/cases/cases_2017.csv" ,header=True)
dp=df1
df_merged=df_spark.join(df1,
               df_spark.ddl_case_id == df1.ddl_case_id, 
               "right")
del df_spark

In [4]:
df_merged = df_merged.drop(col("dist_code"))
df_merged = df_merged.drop(col("cino"))
df_merged = df_merged.drop(col("court_no"))
df_merged = df_merged.drop(col("judge_position"))
df_merged = df_merged.drop(col("type_name"))
df_merged = df_merged.drop(col("purpose_name"))
df_merged = df_merged.drop(col("date_last_list"))
df_merged = df_merged.drop(col("female_adv_def"))
df_merged = df_merged.drop(col("female_petitioner"))
df_merged = df_merged.drop(col("female_adv_pet"))
df_merged=df_merged.drop(df_merged.columns[0])
# df_merged=df_merged.drop(col("ddl_case_id"))
print(df_merged.dtypes)
# df_merged.head(10)

[('criminal', 'string'), ('year', 'string'), ('state_code', 'string'), ('female_defendant', 'string'), ('disp_name', 'string'), ('date_of_filing', 'string'), ('date_of_decision', 'string'), ('date_first_list', 'string'), ('date_next_list', 'string')]

In [5]:
# memory_usage = df_merged.memory_usage().sum()
# print(memory_usage)

In [6]:
df_pandas = df_merged.toPandas()

ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/home/nirmala/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nirmala/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nirmala/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving

In [7]:
del df_merged

In [8]:

df_2017=df_pandas
del df_pandas

In [9]:
df_2017['state_code'].replace(to_replace='01', value="Maharashtra",inplace=True)
df_2017['state_code'].replace(to_replace='02' ,value="Andhra Pradesh",inplace=True)
df_2017['state_code'].replace(to_replace='03' ,value="Karnataka",inplace=True)
df_2017['state_code'].replace(to_replace='04', value="Kerala",inplace=True)
df_2017['state_code'].replace(to_replace='05' ,value="Himachal Pradesh",inplace=True)
df_2017['state_code'].replace(to_replace='06', value="Assam",inplace=True)
df_2017['state_code'].replace(to_replace='07', value="Jharkhand",inplace=True)
df_2017['state_code'].replace(to_replace='08' ,value="Bihar",inplace=True)
df_2017['state_code'].replace(to_replace='09' ,value="Rajasthan",inplace=True)
df_2017['state_code'].replace(to_replace='10' ,value="Tamilnadu",inplace=True)
df_2017['state_code'].replace(to_replace='11',value="Orissa",inplace=True)
df_2017['state_code'].replace(to_replace='12' ,value="Jammu and kashmir",inplace=True)
df_2017['state_code'].replace(to_replace='13' ,value="Uttar pradesh",inplace=True)
df_2017['state_code'].replace(to_replace='14' ,value="Haryana",inplace=True)
df_2017['state_code'].replace(to_replace='15' ,value="Uttarakhand",inplace=True)
df_2017['state_code'].replace(to_replace='16' ,value="West Bengal",inplace=True)
df_2017['state_code'].replace(to_replace='17' ,value="Gujarath",inplace=True)
df_2017['state_code'].replace(to_replace='18' ,value="Chattisgarh",inplace=True)
df_2017['state_code'].replace(to_replace='19' ,value="Mizoram",inplace=True)
df_2017['state_code'].replace(to_replace='20' ,value="Tripura",inplace=True)
df_2017['state_code'].replace(to_replace='21' ,value="Meghalaya",inplace=True)
df_2017['state_code'].replace(to_replace='22' ,value="Punjab",inplace=True)
df_2017['state_code'].replace(to_replace='23' ,value="Madhya Pradesh",inplace=True)
df_2017['state_code'].replace(to_replace='24' , value="Sikkim",inplace=True)
df_2017['state_code'].replace(to_replace='25' ,value="Manipur",inplace=True)
df_2017['state_code'].replace(to_replace='26' ,value="Delhi",inplace=True)
df_2017['state_code'].replace(to_replace='27' ,value="Chandigarh",inplace=True)
df_2017['state_code'].replace(to_replace='29' ,value="Telangana",inplace=True)
df_2017['state_code'].replace(to_replace='30' ,value="Goa",inplace=True)
df_2017['state_code'].replace(to_replace='31' ,value="Diu and daman",inplace=True)
df_2017['state_code'].replace(to_replace='32',value="DNH at silvasa",inplace=True)
df_2017['state_code'].replace(to_replace='33' ,value="Ladakh",inplace=True)

In [10]:
def create_new_column(row):
    if pd.isnull(row['date_next_list']):
        return 1
    else:
        return 0
df_2017['pending'] = df_2017.apply(create_new_column, axis=1)

In [11]:
# df_2017['state_code'].unique()
# df_2017['filing'] = pd.to_datetime(df_2017['date_of_filing'], format='%Y-%m-%d',errors = 'coerce') 
# df_2017['first_list'] = pd.to_datetime(df_2017['date_first_list'], format='%Y-%m-%d',errors = 'coerce') 
# df_2017['decision'] = pd.to_datetime(df_2017['date_of_decision'], format='%Y-%m-%d',errors = 'coerce') 
# df_2017['last_list'] = pd.to_datetime(df_2017['date_next_list'], format='%Y-%m-%d',errors = 'coerce')

In [12]:
# df_2017=df_2017.drop(columns=['date_of_filing','date_of_decision','date_first_list','date_next_list'])
# df_2017['file_reachcourt'] =(df_2017['first_list']-df_2017['filing']).dt.days
# df_2017['file_end'] =(df_2017['last_list']-df_2017['filing']).dt.days
# df_2017['decision_end'] =(df_2017['last_list']-df_2017['decision']).dt.days
# df_2017=df_2017.drop(columns=['filing','first_list','decision','last_list'])

In [13]:
# def replace_negatives(x):
#     if x < 0:
#         return -1
#     return x
# df_2017['file_reachcourt']=df_2017['file_reachcourt'].apply(replace_negatives)
# df_2017['file_end']=df_2017['file_end'].apply(replace_negatives)
# df_2017['decision_end']=df_2017['decision_end'].apply(replace_negatives)
# df_2017
# df_2017.info()
# import numpy as np
# df_2017['file_reachcourt'] = pd.to_numeric(df_2017['file_reachcourt'], errors='coerce')
# df_2017['file_reachcourt'] = df_2017['file_reachcourt'].fillna(-1).replace([np.inf, -np.inf], -1)
# df_2017['file_reachcourt'] = df_2017['file_reachcourt'].astype(int)
# df_2017['file_end'] = pd.to_numeric(df_2017['file_end'], errors='coerce')
# df_2017['file_end'] = df_2017['file_end'].fillna(-1).replace([np.inf, -np.inf], -1)
# df_2017['file_end'] = df_2017['file_end'].astype(int)
# df_2017['decision_end'] = pd.to_numeric(df_2017['decision_end'], errors='coerce')
# df_2017['decision_end'] = df_2017['decision_end'].fillna(-1).replace([np.inf, -np.inf], -1)
# df_2017['decision_end'] = df_2017['decision_end'].astype(int)
# df_2017.info()
# df_2017['decision_end'].unique()
# df_2017['criminal'] = df_2017['criminal'].fillna(-1)
# df_2017['file_reachcourt']=df_2017['file_reachcourt'].fillna(-1)
# df_2017['file_end']=df_2017['file_end'].fillna(-1)
# df_2017['decision_end']=df_2017['decision_end'].fillna(-1)
# df_2017['file_reachcourt']=df_2017['file_reachcourt'].astype(int)
# df_2017['file_end']=df_2017['file_end'].astype(int)
# df_2017['decision_end']=df_2017['decision_end'].astype(int)
# df_2017
# #criminal count
# temp=df_2017
# temp_criminal= temp.drop(temp[temp['criminal']==-1].index)  
# temp_criminal= temp_criminal.drop(temp_criminal[temp_criminal['criminal']==0].index)  
# temp_criminal.info()

# Criminal count

In [14]:

# df_2017['pending'] = df_2017.apply(create_new_column, axis=1)

df_2017['filing'] = pd.to_datetime(df_2017['date_of_filing'], format='%Y-%m-%d',errors = 'coerce') 

df_2017['first_list'] = pd.to_datetime(df_2017['date_first_list'], format='%Y-%m-%d',errors = 'coerce') 

df_2017['decision'] = pd.to_datetime(df_2017['date_of_decision'], format='%Y-%m-%d',errors = 'coerce') 

df_2017['last_list'] = pd.to_datetime(df_2017['date_next_list'], format='%Y-%m-%d',errors = 'coerce') 
df_2017['date_next_list'] = pd.to_datetime(df_2017['date_next_list'], format='%Y-%m-%d',errors = 'coerce')

In [15]:



df_2017['closing'] = df_2017['date_next_list'].dt.year

df_2017['closing']=df_2017['closing'].fillna('1900')


df_2017=df_2017.drop(columns=['date_of_filing','date_of_decision','date_first_list','date_next_list'])

df_2017['file_reachcourt'] =(df_2017['first_list']-df_2017['filing']).dt.days
df_2017['file_end'] =(df_2017['last_list']-df_2017['filing']).dt.days
df_2017['decision_end'] =(df_2017['last_list']-df_2017['decision']).dt.days

In [16]:
df_2017=df_2017.drop(columns=['first_list','decision','last_list'])

def replace_negatives(x):
    if x < 0:
        return -1
    return x
df_2017['file_reachcourt']=df_2017['file_reachcourt'].apply(replace_negatives)


df_2017['file_end']=df_2017['file_end'].apply(replace_negatives)
df_2017['decision_end']=df_2017['decision_end'].apply(replace_negatives)


df_2017



df_2017['criminal'].unique()
df_2017['criminal'].replace(to_replace='0',value='criminal',inplace=True)
df_2017['criminal'].replace(to_replace='1',value='Non-criminal',inplace=True)

df_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4923391 entries, 0 to 4923390
Data columns (total 11 columns):
 #   Column            Dtype
---  ------            -----
 0   criminal          object
 1   year              object
 2   state_code        object
 3   female_defendant  object
 4   disp_name         object
 5   pending           int64
 6   filing            datetime64[ns]
 7   closing           object
 8   file_reachcourt   float64
 9   file_end          float64
 10  decision_end      float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 413.2+ MB

In [17]:
import numpy as np


df_2017['file_reachcourt'] = pd.to_numeric(df_2017['file_reachcourt'], errors='coerce')

# Fill the missing and infinite values with -1
df_2017['file_reachcourt'] = df_2017['file_reachcourt'].fillna(-1).replace([np.inf, -np.inf], -1)

# Convert the 'file_reachcourt' column to integers
df_2017['file_reachcourt'] = df_2017['file_reachcourt'].astype(int)

df_2017['file_end'] = pd.to_numeric(df_2017['file_end'], errors='coerce')

# Fill the missing and infinite values with -1
df_2017['file_end'] = df_2017['file_end'].fillna(-1).replace([np.inf, -np.inf], -1)

# Convert the 'file_end ' column to integers
df_2017['file_end'] = df_2017['file_end'].astype(int)

df_2017['decision_end'] = pd.to_numeric(df_2017['decision_end'], errors='coerce')

# Fill the missing and infinite values with -1
df_2017['decision_end'] = df_2017['decision_end'].fillna(-1).replace([np.inf, -np.inf], -1)

# Convert the 'decision_end' column to integers
df_2017['decision_end'] = df_2017['decision_end'].astype(int)

df_2017.info()

df_2017

df_2017['decision_end'].unique()


# df_2017['criminal'] = df_2017['criminal'].fillna(-1)


# del temp
# del non_criminal_count_2017

#criminal count
temp=df_2017
temp2=df_2017
temp_noncriminal=temp2.drop(temp2[temp2['criminal']=='None'].index)
temp_noncriminal=temp_noncriminal.drop(temp_noncriminal[temp_noncriminal['criminal']=='criminal'].index)
temp_criminal= temp.drop(temp[temp['criminal']=='None'].index)  
temp_criminal= temp_criminal.drop(temp_criminal[temp_criminal['criminal']=='Non-criminal'].index)  

temp_criminal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4923391 entries, 0 to 4923390
Data columns (total 11 columns):
 #   Column            Dtype
---  ------            -----
 0   criminal          object
 1   year              object
 2   state_code        object
 3   female_defendant  object
 4   disp_name         object
 5   pending           int64
 6   filing            datetime64[ns]
 7   closing           object
 8   file_reachcourt   int64
 9   file_end          int64
 10  decision_end      int64
dtypes: datetime64[ns](1), int64(4), object(6)
memory usage: 413.2+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 3149679 entries, 1 to 4923390
Data columns (total 11 columns):
 #   Column            Dtype
---  ------            -----
 0   criminal          object
 1   year              object
 2   state_code        object
 3   female_defendant  object
 4   disp_name         object
 5   pending           int64
 6   filing            datetime64[ns]
 7   closing           object
 8   file_reachcourt   int64
 9   file_end          int64
 10  decision_end      int64
dtypes: datetime64[ns](1), int64(4), object(6)
memory usage: 288.4+ MB

# Criminal count

In [18]:
criminal_count_2017 = temp_criminal["state_code"].value_counts().reset_index()

# Rename the "index" and "Year" columns
criminal_count_2017['state_code']=criminal_count_2017['state_code'].sort_values()
criminal_count_2017.rename(columns={"index": "state", "state_code": "criminal_count"}, inplace=True)

criminal_count_2017

criminal_count_2017.info()

# new_rows = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'criminal_count' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})


# criminal_count_2017= pd.concat([new_rows, criminal_count_2017], ignore_index=True)


criminal_count_2017['state']=criminal_count_2017['state'].sort_values()


criminal_count_2017=criminal_count_2017.sort_values(by='state')

criminal_count_2017.insert(2, 'Year', 2017)


criminal_count_2017=criminal_count_2017.reset_index()

criminal_count_2017=criminal_count_2017.drop(columns=['index'])

del temp_criminal

criminal_count_2017


criminal_count_2017['criminal_perlakh']=criminal_count_2017['criminal_count']/100000

non_criminal_count_2017 = temp_noncriminal["state_code"].value_counts().reset_index()

# Rename the "index" and "Year" columns
non_criminal_count_2017['state_code']=non_criminal_count_2017['state_code'].sort_values()
non_criminal_count_2017.rename(columns={"index": "state", "state_code": "noncriminal_count"}, inplace=True)

non_criminal_count_2017

non_criminal_count_2017.info()

# new_rows = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'noncriminal_count' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})


# non_criminal_count_2017= pd.concat([new_rows, non_criminal_count_2017], ignore_index=True)


non_criminal_count_2017['state']=non_criminal_count_2017['state'].sort_values()


non_criminal_count_2017=non_criminal_count_2017.sort_values(by='state')

# non_criminal_count_2017.insert(2, 'Year', 2017)


non_criminal_count_2017=non_criminal_count_2017.reset_index()

non_criminal_count_2017=non_criminal_count_2017.drop(columns=['index'])
non_criminal_count_2017

df_criminal_not=pd.merge(criminal_count_2017,non_criminal_count_2017,on='state')

df_criminal_not

df_criminal_not['noncriminal_perlakh']=df_criminal_not['noncriminal_count']/100000

df_criminal_not

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   state           32 non-null     object
 1   criminal_count  32 non-null     int64
dtypes: int64(1), object(1)
memory usage: 640.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   state              32 non-null     object
 1   noncriminal_count  32 non-null     int64
dtypes: int64(1), object(1)
memory usage: 640.0+ bytes

,state,criminal_count,Year,criminal_perlakh,noncriminal_count,noncriminal_perlakh
0,Andhra Pradesh,79525,2017,0.79525,45845,0.45845
1,Assam,52800,2017,0.52800,36124,0.36124
2,Bihar,54902,2017,0.54902,132444,1.32444
3,Chandigarh,10583,2017,0.10583,1063,0.01063
4,Chattisgarh,42355,2017,0.42355,24785,0.24785
5,DNH at silvasa,149,2017,0.00149,173,0.00173
6,Delhi,97030,2017,0.97030,38537,0.38537
7,Diu and daman,385,2017,0.00385,229,0.00229
8,Goa,9178,2017,0.09178,2371,0.02371
9,Gujarath,185540,2017,1.85540,88104,0.88104
10,Haryana,173864,2017,1.73864,54964,0.54964
11,Himachal Pradesh,41616,2017,0.41616,14784,0.14784
12,Jammu and kashmir,23208,2017,0.23208,7365,0.07365
13,Jharkhand,20621,2017,0.20621,47497,0.47497
14,Karnataka,298348,2017,2.98348,125317,1.25317
15,Kerala,181271,2017,1.81271,134457,1.34457
16,Ladakh,95,2017,0.00095,27,0.00027
17,Madhya Pradesh,157515,2017,1.57515,131364,1.31364
18,Maharashtra,356258,2017,3.56258,151728,1.51728
19,Manipur,2982,2017,0.02982,2492,0.02492
20,Meghalaya,2204,2017,0.02204,485,0.00485
21,Mizoram,463,2017,0.00463,206,0.00206
22,Orissa,69388,2017,0.69388,46615,0.46615
23,Punjab,141987,2017,1.41987,55161,0.55161
24,Rajasthan,204990,2017,2.04990,147316,1.47316
25,Sikkim,905,2017,0.00905,745,0.00745
26,Tamilnadu,175175,2017,1.75175,81654,0.81654
27,Telangana,42992,2017,0.42992,40997,0.40997
28,Tripura,2380,2017,0.02380,2064,0.02064
29,Uttar pradesh,590719,2017,5.90719,392831,3.92831
30,Uttarakhand,39058,2017,0.39058,6570,0.06570
31,West Bengal,91193,2017,0.91193,84525,0.84525

In [19]:
# # 
# df_2017['pending'] = df_2017.apply(create_new_column, axis=1)

# df_2017['filing'] = pd.to_datetime(df_2017['date_of_filing'], format='%Y-%m-%d',errors = 'coerce') 

# df_2017['first_list'] = pd.to_datetime(df_2017['date_first_list'], format='%Y-%m-%d',errors = 'coerce') 

# df_2017['decision'] = pd.to_datetime(df_2017['date_of_decision'], format='%Y-%m-%d',errors = 'coerce') 

# df_2017['last_list'] = pd.to_datetime(df_2017['date_next_list'], format='%Y-%m-%d',errors = 'coerce') 
# df_2017['date_next_list'] = pd.to_datetime(df_2017['date_next_list'], format='%Y-%m-%d',errors = 'coerce') 






# df_2017['closing'] = df_2017['date_next_list'].dt.year

# df_2017['closing']=df_2017['closing'].fillna('1900')


# df_2017=df_2017.drop(columns=['date_of_filing','date_of_decision','date_first_list','date_next_list'])

# df_2017['file_reachcourt'] =(df_2017['first_list']-df_2017['filing']).dt.days
# df_2017['file_end'] =(df_2017['last_list']-df_2017['filing']).dt.days
# df_2017['decision_end'] =(df_2017['last_list']-df_2017['decision']).dt.days




# df_2017=df_2017.drop(columns=['first_list','decision','last_list'])

# def replace_negatives(x):
#     if x < 0:
#         return -1
#     return x
# df_2017['file_reachcourt']=df_2017['file_reachcourt'].apply(replace_negatives)


# df_2017['file_end']=df_2017['file_end'].apply(replace_negatives)
# df_2017['decision_end']=df_2017['decision_end'].apply(replace_negatives)


# df_2017



# df_2017['criminal'].unique()
# df_2017['criminal'].replace(to_replace='0',value='criminal',inplace=True)
# df_2017['criminal'].replace(to_replace='1',value='Non-criminal',inplace=True)

# df_2017.info()



# import numpy as np


# df_2017['file_reachcourt'] = pd.to_numeric(df_2017['file_reachcourt'], errors='coerce')

# # Fill the missing and infinite values with -1
# df_2017['file_reachcourt'] = df_2017['file_reachcourt'].fillna(-1).replace([np.inf, -np.inf], -1)

# # Convert the 'file_reachcourt' column to integers
# df_2017['file_reachcourt'] = df_2017['file_reachcourt'].astype(int)

# df_2017['file_end'] = pd.to_numeric(df_2017['file_end'], errors='coerce')

# # Fill the missing and infinite values with -1
# df_2017['file_end'] = df_2017['file_end'].fillna(-1).replace([np.inf, -np.inf], -1)

# # Convert the 'file_end ' column to integers
# df_2017['file_end'] = df_2017['file_end'].astype(int)

# df_2017['decision_end'] = pd.to_numeric(df_2017['decision_end'], errors='coerce')

# # Fill the missing and infinite values with -1
# df_2017['decision_end'] = df_2017['decision_end'].fillna(-1).replace([np.inf, -np.inf], -1)

# # Convert the 'decision_end' column to integers
# df_2017['decision_end'] = df_2017['decision_end'].astype(int)

# df_2017.info()

# df_2017

# df_2017['decision_end'].unique()


# # df_2017['criminal'] = df_2017['criminal'].fillna(-1)


# # del temp
# # del non_criminal_count_2017

# #criminal count
# temp=df_2017
# temp2=df_2017
# temp_noncriminal=temp2.drop(temp2[temp2['criminal']=='None'].index)
# temp_noncriminal=temp_noncriminal.drop(temp_noncriminal[temp_noncriminal['criminal']=='criminal'].index)
# temp_criminal= temp.drop(temp[temp['criminal']=='None'].index)  
# temp_criminal= temp_criminal.drop(temp_criminal[temp_criminal['criminal']=='Non-criminal'].index)  

# temp_criminal.info()

# # Criminal count 

# criminal_count_2017 = temp_criminal["state_code"].value_counts().reset_index()

# # Rename the "index" and "Year" columns
# criminal_count_2017['state_code']=criminal_count_2017['state_code'].sort_values()
# criminal_count_2017.rename(columns={"index": "state", "state_code": "criminal_count"}, inplace=True)

# criminal_count_2017

# criminal_count_2017.info()

# # new_rows = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'criminal_count' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})


# # criminal_count_2017= pd.concat([new_rows, criminal_count_2017], ignore_index=True)


# criminal_count_2017['state']=criminal_count_2017['state'].sort_values()


# criminal_count_2017=criminal_count_2017.sort_values(by='state')

# criminal_count_2017.insert(2, 'Year', 2017)


# criminal_count_2017=criminal_count_2017.reset_index()

# criminal_count_2017=criminal_count_2017.drop(columns=['index'])

# del temp_criminal

# criminal_count_2017


# criminal_count_2017['criminal_perlakh']=criminal_count_2017['criminal_count']/100000

# non_criminal_count_2017 = temp_noncriminal["state_code"].value_counts().reset_index()

# # Rename the "index" and "Year" columns
# non_criminal_count_2017['state_code']=non_criminal_count_2017['state_code'].sort_values()
# non_criminal_count_2017.rename(columns={"index": "state", "state_code": "noncriminal_count"}, inplace=True)

# non_criminal_count_2017

# non_criminal_count_2017.info()

# # new_rows = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'noncriminal_count' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})


# # non_criminal_count_2017= pd.concat([new_rows, non_criminal_count_2017], ignore_index=True)


# non_criminal_count_2017['state']=non_criminal_count_2017['state'].sort_values()


# non_criminal_count_2017=non_criminal_count_2017.sort_values(by='state')

# # non_criminal_count_2017.insert(2, 'Year', 2017)


# non_criminal_count_2017=non_criminal_count_2017.reset_index()

# non_criminal_count_2017=non_criminal_count_2017.drop(columns=['index'])
# non_criminal_count_2017

# df_criminal_not=pd.merge(criminal_count_2017,non_criminal_count_2017,on='state')

# df_criminal_not

# df_criminal_not['noncriminal_perlakh']=df_criminal_not['noncriminal_count']/100000

# df_criminal_not

KeyError: 'date_next_list'

# Pending Cases in 2017

In [20]:
# del pending_Cases

In [21]:
del temp
temp=df_2017

temp=temp.drop(temp[temp['pending']==0].index)

pending_Cases = temp["state_code"].value_counts().reset_index()

# Rename the "index" and "Year" columns
pending_Cases['state_code']=pending_Cases['state_code'].sort_values()
pending_Cases.rename(columns={"index": "state", "state_code": "pendingcases_count"}, inplace=True)
new_rows_pending = pd.DataFrame({'state' : ['DNH at silvasa','Ladakh','Sikkim'], 'pendingcases_count' : [0,0,0]})

pending_Cases= pd.concat([new_rows_pending, pending_Cases], ignore_index=True)

# pending_Cases

# del pending_Cases


pending_Cases=pending_Cases.sort_values(by='state')

pending_Cases

pending_Cases=pending_Cases.reset_index()

pending_Cases=pending_Cases.drop(columns=['index'])  

pending_Cases.info()

pending_Cases.insert(2, 'Year', 2017)


pending_Cases

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   state               32 non-null     object
 1   pendingcases_count  32 non-null     int64
dtypes: int64(1), object(1)
memory usage: 640.0+ bytes

                state  pendingcases_count  Year
0      Andhra Pradesh                 646  2017
1               Assam                1140  2017
2               Bihar                2451  2017
3          Chandigarh                   2  2017
4         Chattisgarh                4468  2017
5      DNH at silvasa                   0  2017
6               Delhi                  46  2017
7       Diu and daman                  39  2017
8                 Goa                   3  2017
9            Gujarath                 225  2017
10            Haryana                1373  2017
11   Himachal Pradesh                2584  2017
12  Jammu and kashmir                 343  2017
13          Jharkhand                 449  2017
14          Karnataka               21803  2017
15             Kerala                 592  2017
16             Ladakh                   0  2017
17     Madhya Pradesh                4638  2017
18        Maharashtra               10773  2017
19            Manipur                  12  2017
20          Meghalaya                  10  2017
21            Mizoram                   1  2017
22             Orissa                3902  2017
23             Punjab               13427  2017
24          Rajasthan               49300  2017
25             Sikkim                   0  2017
26          Tamilnadu               15554  2017
27          Telangana                 208  2017
28            Tripura                  11  2017
29      Uttar pradesh               28817  2017
30        Uttarakhand                 448  2017
31        West Bengal                3065  2017

# Average Time to reach court after filing per 1 lakh cases

In [22]:
# Average Time to reach court after filing per 1 lakh cases

# del temp
temp=df_2017

avg_file_court=temp.drop(temp[temp['file_reachcourt'] < 0].index)
# del avg_file_court

avg_file_court

# filing_reach = df["file_reachcourt"].value_counts().reset_index()
avg_file_court = avg_file_court.groupby('state_code')
# df_mean = filing_reach['file_reachcourt'].mean()

def avg_days(group,column):
    return group[column].mean() / group[column].count() * 100000

df_avg_days = avg_file_court.apply(avg_days,"file_reachcourt")

# # Rename the "index" and "Year" columns
# year_counts_end.rename(columns={"index": "year", "year2": "count_of_end"}, inplace=True)
# year_counts_end
df_avg_days.info()
del avg_file_court

file_court_avg=df_avg_days.to_frame().reset_index()

# pandas_s.info()
file_court_avg.rename(columns={"state_code": "state", 0: "avg_filecourt_per1lakhcases"}, inplace=True)
file_court_avg

# new_rows_file_court_avg = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'avg_filecourt_per1lakhcases' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})

# file_court_avg= pd.concat([new_rows_file_court_avg, file_court_avg], ignore_index=True)

file_court_avg
del df_avg_days


file_court_avg=file_court_avg.sort_values(by='state')




file_court_avg.info()



file_court_avg


file_court_avg=file_court_avg.reset_index()
file_court_avg=file_court_avg.drop(columns=['index'])  


file_court_avg.info()

file_court_avg.insert(2, 'Year', 2017)


# file_court_avg=file_court_avg.drop(columns=['Year'])  
file_court_avg

file_court_avg['avg_filecourt_per1lakhcases']=file_court_avg['avg_filecourt_per1lakhcases'].astype(int)

file_court_avg

<class 'pandas.core.series.Series'>
Index: 32 entries, Andhra Pradesh to West Bengal
Series name: None
Non-Null Count  Dtype
--------------  -----
32 non-null     float64
dtypes: float64(1)
memory usage: 512.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Int64Index: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   state                        32 non-null     object
 1   avg_filecourt_per1lakhcases  32 non-null     float64
dtypes: float64(1), object(1)
memory usage: 768.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   state                        32 non-null     object
 1   avg_filecourt_per1lakhcases  32 non-null     float64
dtypes: float64(1), object(1)
memory usage: 640.0+ bytes

                state  avg_filecourt_per1lakhcases  Year
0      Andhra Pradesh                           60  2017
1               Assam                           68  2017
2               Bihar                           63  2017
3          Chandigarh                           19  2017
4         Chattisgarh                           47  2017
5      DNH at silvasa                         4190  2017
6               Delhi                           21  2017
7       Diu and daman                         2509  2017
8                 Goa                          194  2017
9            Gujarath                           10  2017
10            Haryana                            9  2017
11   Himachal Pradesh                           68  2017
12  Jammu and kashmir                          478  2017
13          Jharkhand                           47  2017
14          Karnataka                            7  2017
15             Kerala                           27  2017
16             Ladakh                        66220  2017
17     Madhya Pradesh                           11  2017
18        Maharashtra                            5  2017
19            Manipur                          205  2017
20          Meghalaya                           82  2017
21            Mizoram                        12556  2017
22             Orissa                           79  2017
23             Punjab                            5  2017
24          Rajasthan                           15  2017
25             Sikkim                          452  2017
26          Tamilnadu                           21  2017
27          Telangana                          150  2017
28            Tripura                          666  2017
29      Uttar pradesh                            5  2017
30        Uttarakhand                           95  2017
31        West Bengal                           36  2017

# Average Time to End case after filing per 1 lakh cases in 2017

In [23]:
temp=df_2017

avg_file_end=temp.drop(temp[temp['file_end'] < 0].index)
# del avg_file_end

avg_file_end

# filing_reach = df["file_end"].value_counts().reset_index()
avg_file_end = avg_file_end.groupby('state_code')
# df_mean = filing_reach['file_end'].mean()

def avg_days(group,column):
    return group[column].mean() / group[column].count() * 100000

df_avg_days = avg_file_end.apply(avg_days,"file_end")

# # Rename the "index" and "Year" columns
# year_counts_end.rename(columns={"index": "year", "year2": "count_of_end"}, inplace=True)
# year_counts_end
df_avg_days

file_End_avg=df_avg_days.to_frame().reset_index()

# pandas_s.info()
file_End_avg.rename(columns={"state_code": "state", 0: "avg_fileend_per1lakhcases"}, inplace=True)
file_End_avg

# new_rows_file_End_avg = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'avg_fileend_per1lakhcases' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})

# file_End_avg= pd.concat([new_rows_file_End_avg, file_End_avg], ignore_index=True)

# file_End_avg


file_End_avg=file_End_avg.sort_values(by='state')




file_End_avg.info()



file_End_avg


file_End_avg=file_End_avg.reset_index()
file_End_avg=file_End_avg.drop(columns=['index'])  


file_End_avg.info()

file_End_avg.insert(2, 'Year', 2017)


file_End_avg

file_End_avg['avg_fileend_per1lakhcases']=file_End_avg['avg_fileend_per1lakhcases'].astype(int)

file_End_avg
del avg_file_end
del df_avg_days

file_End_avg['avg_fileend_per1lakhcases']=file_End_avg['avg_fileend_per1lakhcases'].astype(int)

file_End_avg.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   state                      32 non-null     object
 1   avg_fileend_per1lakhcases  32 non-null     float64
dtypes: float64(1), object(1)
memory usage: 768.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   state                      32 non-null     object
 1   avg_fileend_per1lakhcases  32 non-null     float64
dtypes: float64(1), object(1)
memory usage: 640.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 3 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   state                      32 non-null     object
 1   avg_fileend_per1lakhcases  32 non-null     int64
 2   Year                       32 non-null     int64
dtypes: int64(2), object(1)
memory usage: 896.0+ bytes

# Average Time to End case after decision per 1 lakh cases in 2012

In [24]:
del temp
temp=df_2017

avg_decision_end=temp.drop(temp[temp['decision_end'] < 0].index)
# del avg_decision_end

avg_decision_end

# filing_reach = df["decision_end"].value_counts().reset_index()
avg_decision_end = avg_decision_end.groupby('state_code')
# df_mean = filing_reach['decision_end'].mean()

def avg_days(group,column):
    return group[column].mean() / group[column].count() * 100000

df_avg_days = avg_decision_end.apply(avg_days,"decision_end")

# # Rename the "index" and "Year" columns
# year_counts_end.rename(columns={"index": "year", "year2": "count_of_end"}, inplace=True)
# year_counts_end
df_avg_days.info()

decision_end_avg=df_avg_days.to_frame().reset_index()

# pandas_s.info()
decision_end_avg.rename(columns={"state_code": "state", 0: "avg_decision_end_per1lakhcases"}, inplace=True)
decision_end_avg

# new_rows_decision_end_avg = pd.DataFrame({'state' : [ 'Kerala', 'Himachal Pradesh', 'Assam', 'Jharkhand', 'Bihar', 'Rajasthan', 'Tamilnadu', 'Orissa','Jammu and kashmir','Uttar pradesh', 'Haryana','Uttarakhand','West Bengal','Gujarath','Chattisgarh','Mizoram','Tripura','Meghalaya','Punjab','Madhya Pradesh','Sikkim','Manipur','Delhi','Chandigarh','Telangana','Goa','Diu and daman','DNH at silvasa','Ladakh'], 'avg_decision_end_per1lakhcases' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 ]})

# decision_end_avg= pd.concat([new_rows_decision_end_avg, decision_end_avg], ignore_index=True)

# decision_end_avg


decision_end_avg=decision_end_avg.sort_values(by='state')




decision_end_avg.info()



decision_end_avg


decision_end_avg=decision_end_avg.reset_index()
decision_end_avg=decision_end_avg.drop(columns=['index'])  


decision_end_avg.info()

decision_end_avg.insert(2, 'Year', 2017)


decision_end_avg

decision_end_avg['avg_decision_end_per1lakhcases']=decision_end_avg['avg_decision_end_per1lakhcases'].astype(int)

decision_end_avg
del df_avg_days
del avg_decision_end

<class 'pandas.core.series.Series'>
Index: 32 entries, Andhra Pradesh to West Bengal
Series name: None
Non-Null Count  Dtype
--------------  -----
32 non-null     float64
dtypes: float64(1)
memory usage: 512.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Int64Index: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   state                           32 non-null     object
 1   avg_decision_end_per1lakhcases  32 non-null     float64
dtypes: float64(1), object(1)
memory usage: 768.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   state                           32 non-null     object
 1   avg_decision_end_per1lakhcases  32 non-null     float64
dtypes: float64(1), object(1)
memory usage: 640.0+ bytes

# Withdrawal

In [24]:
# del withdrawal

In [25]:
del temp
temp=df_2017

withdrawal=temp[temp['disp_name'] == '51']
# del avg_decision_end

# withdrawal
withdrawal = withdrawal["state_code"].value_counts().reset_index()

# Rename the "index" and "Year" columns
withdrawal['state_code']=withdrawal['state_code'].sort_values()
withdrawal.rename(columns={"index": "state", "state_code": "withdrawal_count"}, inplace=True)
new_rows_withdrawal = pd.DataFrame({'state' : [ 'Andhra Pradesh','Assam','DNH at silvasa','Diu and daman','Goa','Gujarath','Himachal Pradesh','Karnataka','Ladakh','Madhya Pradesh','Maharashtra','Manipur','Sikkim','Mizoram','Tamilnadu','Telangana','Tripura','Uttarakhand','West Bengal'], 'withdrawal_count' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]})
# withdrawal
withdrawal= pd.concat([new_rows_withdrawal, withdrawal], ignore_index=True)
# withdrawal
withdrawal=withdrawal.sort_values(by='state')
withdrawal.info()
withdrawal
withdrawal=withdrawal.reset_index()
withdrawal=withdrawal.drop(columns=['index'])  
withdrawal.info()
withdrawal.insert(2, 'Year', 2017)
withdrawal['state']

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32 entries, 0 to 18
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             32 non-null     object
 1   withdrawal_count  32 non-null     int64
dtypes: int64(1), object(1)
memory usage: 768.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             32 non-null     object
 1   withdrawal_count  32 non-null     int64
dtypes: int64(1), object(1)
memory usage: 640.0+ bytes

0        Andhra Pradesh
1                 Assam
2                 Bihar
3            Chandigarh
4           Chattisgarh
5        DNH at silvasa
6                 Delhi
7         Diu and daman
8                   Goa
9              Gujarath
10              Haryana
11     Himachal Pradesh
12    Jammu and kashmir
13            Jharkhand
14            Karnataka
15               Kerala
16               Ladakh
17       Madhya Pradesh
18          Maharashtra
19              Manipur
20            Meghalaya
21              Mizoram
22               Orissa
23               Punjab
24            Rajasthan
25               Sikkim
26            Tamilnadu
27            Telangana
28              Tripura
29        Uttar pradesh
30          Uttarakhand
31          West Bengal
Name: state, dtype: object

# Prison

In [35]:
# del prison

In [26]:
# del temp
temp=df_2017
prison=temp[temp['disp_name'] == '38']
# del avg_decision_end
prison
prison = prison["state_code"].value_counts().reset_index()
# Rename the "index" and "Year" columns
prison['state_code']=prison['state_code'].sort_values()
prison.rename(columns={"index": "state", "state_code": "prison_count"}, inplace=True)
new_rows_prison = pd.DataFrame({'state' : ['Andhra Pradesh','Diu and daman','Goa','Haryana','Himachal Pradesh','Ladakh','Madhya Pradesh','Mizoram','Punjab','Tamilnadu','Telangana'], 'prison_count' : [0,0,0,0,0,0,0,0,0,0,0]})

prison= pd.concat([new_rows_prison, prison], ignore_index=True)
prison
prison=prison.sort_values(by='state')
prison=prison.reset_index()
prison=prison.drop(columns=['index'])  
prison.insert(2, 'Year', 2017)
prison.info()
prison
# del dismissed_2012

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         32 non-null     object
 1   prison_count  32 non-null     int64
 2   Year          32 non-null     int64
dtypes: int64(2), object(1)
memory usage: 896.0+ bytes

                state  prison_count  Year
0      Andhra Pradesh             0  2017
1               Assam           566  2017
2               Bihar             2  2017
3          Chandigarh             2  2017
4         Chattisgarh           189  2017
5      DNH at silvasa             2  2017
6               Delhi           833  2017
7       Diu and daman             0  2017
8                 Goa             0  2017
9            Gujarath         33884  2017
10            Haryana             0  2017
11   Himachal Pradesh             0  2017
12  Jammu and kashmir             3  2017
13          Jharkhand          1342  2017
14          Karnataka         31053  2017
15             Kerala         11728  2017
16             Ladakh             0  2017
17     Madhya Pradesh             0  2017
18        Maharashtra          6998  2017
19            Manipur             3  2017
20          Meghalaya             5  2017
21            Mizoram             0  2017
22             Orissa           159  2017
23             Punjab             0  2017
24          Rajasthan          8047  2017
25             Sikkim            24  2017
26          Tamilnadu             0  2017
27          Telangana             0  2017
28            Tripura            26  2017
29      Uttar pradesh            33  2017
30        Uttarakhand           405  2017
31        West Bengal          3652  2017

# Dismissed cases

In [44]:
del dismissed

In [27]:
del temp
temp=df_2017
dismissed=temp[temp['disp_name'] == '22']
# del avg_decision_end
# dismissed
dismissed = dismissed["state_code"].value_counts().reset_index()
# Rename the "index" and "Year" columns
dismissed['state_code']=dismissed['state_code'].sort_values()
dismissed.rename(columns={"index": "state", "state_code": "dismissed_count"}, inplace=True)
new_rows_dismissed = pd.DataFrame({'state' : ['Andhra Pradesh','Assam','DNH at silvasa','Diu and daman','Goa','Gujarath','Himachal Pradesh','Ladakh','Madhya Pradesh','Manipur','Meghalaya','Mizoram','Punjab','Tamilnadu','Telangana','Uttarakhand'], 'dismissed_count' : [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]})
# # dismissed
dismissed= pd.concat([new_rows_dismissed, dismissed], ignore_index=True)
dismissed
dismissed=dismissed.sort_values(by='state')
dismissed=dismissed.reset_index()
dismissed=dismissed.drop(columns=['index'])  
dismissed.insert(2, 'Year', 2017)
dismissed

                state  dismissed_count  Year
0      Andhra Pradesh                0  2017
1               Assam                0  2017
2               Bihar                9  2017
3          Chandigarh                2  2017
4         Chattisgarh               93  2017
5      DNH at silvasa                0  2017
6               Delhi               11  2017
7       Diu and daman                0  2017
8                 Goa                0  2017
9            Gujarath                0  2017
10            Haryana               65  2017
11   Himachal Pradesh                0  2017
12  Jammu and kashmir                5  2017
13          Jharkhand               16  2017
14          Karnataka               32  2017
15             Kerala                6  2017
16             Ladakh                0  2017
17     Madhya Pradesh                0  2017
18        Maharashtra               36  2017
19            Manipur                0  2017
20          Meghalaya                0  2017
21            Mizoram                0  2017
22             Orissa                7  2017
23             Punjab                0  2017
24          Rajasthan              129  2017
25             Sikkim                2  2017
26          Tamilnadu                0  2017
27          Telangana                0  2017
28            Tripura                1  2017
29      Uttar pradesh              127  2017
30        Uttarakhand                0  2017
31        West Bengal                1  2017

# Merging

In [28]:
df_merged=pd.merge(dismissed,prison,on='state')
df_merged=pd.merge(df_merged,withdrawal,on='state')
df_merged=pd.merge(df_merged,decision_end_avg,on='state')
df_merged=pd.merge(df_merged,file_End_avg,on='state')
df_merged=pd.merge(df_merged,file_court_avg,on='state')
# df_merged=pd.merge(df_merged,pending_Cases,on='state')
df_merged=pd.merge(df_merged,df_criminal_not,on='state')

/tmp/ipykernel_3779/395889879.py:3: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Year_x'} in the result is deprecated and will raise a MergeError in a future version.
  df_merged=pd.merge(df_merged,decision_end_avg,on='state')
/tmp/ipykernel_3779/395889879.py:5: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Year_x'} in the result is deprecated and will raise a MergeError in a future version.
  df_merged=pd.merge(df_merged,file_court_avg,on='state')

In [30]:
df_merged=df_merged.drop(columns='Year_x')
df_merged=df_merged.drop(columns='Year_y')
# df_merged=df_merged.drop(df_merged.columns[[3, 6, 9]],axis = 1)
df_merged['year']=[2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017,2017]
df_merged=df_merged.reindex(columns=['year','state','dismissed_count','prison_count','withdrawal_count','avg_decision_end_per1lakhcases','avg_fileend_per1lakhcases','avg_filecourt_per1lakhcases','criminal_count','criminal_perlakh','noncriminal_count','noncriminal_perlakh'])
df_merged.info()
df_merged.to_csv('2017_filtered.csv', index=False)
df_merged.to_csv('2017_filtered_copy.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   year                            32 non-null     int64
 1   state                           32 non-null     object
 2   dismissed_count                 32 non-null     int64
 3   prison_count                    32 non-null     int64
 4   withdrawal_count                32 non-null     int64
 5   avg_decision_end_per1lakhcases  32 non-null     int64
 6   avg_fileend_per1lakhcases       32 non-null     int64
 7   avg_filecourt_per1lakhcases     32 non-null     int64
 8   criminal_count                  32 non-null     int64
 9   criminal_perlakh                32 non-null     float64
 10  noncriminal_count               32 non-null     int64
 11  noncriminal_perlakh             32 non-null     float64
dtypes: float64(2), int64(9), object(1)
memory usage: 3.2+ KB

In [31]:
df_merged

,year,state,dismissed_count,prison_count,withdrawal_count,avg_decision_end_per1lakhcases,avg_fileend_per1lakhcases,avg_filecourt_per1lakhcases,criminal_count,criminal_perlakh,noncriminal_count,noncriminal_perlakh
0,2017,Andhra Pradesh,0,0,0,0,310,60,79525,0.79525,45845,0.45845
1,2017,Assam,0,566,0,0,339,68,52800,0.52800,36124,0.36124
2,2017,Bihar,9,2,857,6,241,63,54902,0.54902,132444,1.32444
3,2017,Chandigarh,2,2,39,0,2903,19,10583,0.10583,1063,0.01063
4,2017,Chattisgarh,93,189,42,0,477,47,42355,0.42355,24785,0.24785
5,2017,DNH at silvasa,0,2,0,0,95954,4190,149,0.00149,173,0.00173
6,2017,Delhi,11,833,5034,0,256,21,97030,0.97030,38537,0.38537
7,2017,Diu and daman,0,0,0,0,24610,2509,385,0.00385,229,0.00229
8,2017,Goa,0,0,0,0,2104,194,9178,0.09178,2371,0.02371
9,2017,Gujarath,0,33884,0,0,101,10,185540,1.85540,88104,0.88104
10,2017,Haryana,65,0,4149,0,131,9,173864,1.73864,54964,0.54964
11,2017,Himachal Pradesh,0,0,0,0,575,68,41616,0.41616,14784,0.14784
12,2017,Jammu and kashmir,5,3,5,0,1562,478,23208,0.23208,7365,0.07365
13,2017,Jharkhand,16,1342,113,1,468,47,20621,0.20621,47497,0.47497
14,2017,Karnataka,32,31053,0,1,67,7,298348,2.98348,125317,1.25317
15,2017,Kerala,6,11728,1,0,123,27,181271,1.81271,134457,1.34457
16,2017,Ladakh,0,0,0,0,305769,66220,95,0.00095,27,0.00027
17,2017,Madhya Pradesh,0,0,0,0,114,11,157515,1.57515,131364,1.31364
18,2017,Maharashtra,36,6998,0,0,78,5,356258,3.56258,151728,1.51728
19,2017,Manipur,0,3,0,5,2399,205,2982,0.02982,2492,0.02492
20,2017,Meghalaya,0,5,1,6,6278,82,2204,0.02204,485,0.00485
21,2017,Mizoram,0,0,0,0,46289,12556,463,0.00463,206,0.00206
22,2017,Orissa,7,159,40,4,547,79,69388,0.69388,46615,0.46615
23,2017,Punjab,0,0,982,0,148,5,141987,1.41987,55161,0.55161
24,2017,Rajasthan,129,8047,10,0,110,15,204990,2.04990,147316,1.47316
25,2017,Sikkim,2,24,0,0,7315,452,905,0.00905,745,0.00745
26,2017,Tamilnadu,0,0,0,0,149,21,175175,1.75175,81654,0.81654
27,2017,Telangana,0,0,0,0,544,150,42992,0.42992,40997,0.40997
28,2017,Tripura,1,26,0,7,7900,666,2380,0.02380,2064,0.02064
29,2017,Uttar pradesh,127,33,1150,0,35,5,590719,5.90719,392831,3.92831
30,2017,Uttarakhand,0,405,0,0,807,95,39058,0.39058,6570,0.06570
31,2017,West Bengal,1,3652,0,0,280,36,91193,0.91193,84525,0.84525

In [32]:
del prison
del withdrawal
del decision_end_avg
del file_End_avg
del file_court_avg
# del pending_Cases
# del criminal_count