In [1]:
import pandas as pd

In [2]:
df0=pd.read_csv('/home/nirmala/Videos/2010_filtered.csv')

In [3]:
df1=pd.read_csv('/home/nirmala/Videos/2011_filtered.csv')

In [4]:
df2=pd.read_csv('/home/nirmala/Videos/2012_filtered.csv')

In [5]:
df3=pd.read_csv('/home/nirmala/Videos/2013_filtered.csv')

In [6]:
df4=pd.read_csv('/home/nirmala/Videos/2014_filtered.csv')

In [7]:
df5=pd.read_csv('/home/nirmala/Videos/2015_filtered.csv')

In [8]:
df6=pd.read_csv('/home/nirmala/Videos/2016_filtered.csv')

In [9]:
df7=pd.read_csv('/home/nirmala/Videos/2017_filtered.csv')

In [10]:
df8=pd.read_csv('/home/nirmala/Videos/2018_filtered.csv')

In [11]:
df=pd.concat([df0,df1])
df=pd.concat([df,df2])
df=pd.concat([df,df3])
df=pd.concat([df,df4])
df=pd.concat([df,df5])
df=pd.concat([df,df6])
df=pd.concat([df,df7])
df=pd.concat([df,df8])

In [12]:
df

,year,state,dismissed_count,prison_count,withdrawal_count,avg_decision_end_per1lakhcases,avg_fileend_per1lakhcases,avg_filecourt_per1lakhcases,pendingcases_count,pending_casesperlakh,criminal_count,criminal_perlakh,noncriminal_count,noncriminal_perlakh
0,2010,Andhra Pradesh,27690,0,1332,0,888,353,200.0,0.002,88892,0.88892,46002,0.46002
1,2010,Assam,0,0,0,0,0,0,0.0,0.000,0,0.00000,0,0.00000
2,2010,Bihar,0,0,0,0,0,0,0.0,0.000,0,0.00000,0,0.00000
3,2010,Chandigarh,0,0,0,0,0,0,0.0,0.000,0,0.00000,0,0.00000
4,2010,Chattisgarh,0,0,0,0,0,0,0.0,0.000,0,0.00000,0,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27,2018,Telangana,0,0,0,1,393,129,0.0,0.000,32018,0.32018,27368,0.27368
28,2018,Tripura,1,23,0,13,6606,855,0.0,0.000,1669,0.01669,1367,0.01367
29,2018,Uttar pradesh,75,9,535,0,25,4,0.0,0.000,435728,4.35728,350077,3.50077
30,2018,Uttarakhand,1,249,0,1,536,115,0.0,0.000,32287,0.32287,11551,0.11551
31,2018,West Bengal,0,6281,0,0,233,24,0.0,0.000,59874,0.59874,57621,0.57621

In [13]:
df.to_csv('merged_final.csv', index=False)
df.to_csv('merged_final_copy_after_filter.csv', index=False)