In [2]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
import pandas as pd
spark = SparkSession.builder \
    .appName('Read CSV File into DataFrame') \
    .config('spark.executor.memory', '10g') \
    .config('spark.driver.memory', '50g') \
    .getOrCreate()
# spark = SparkSession.builder.appName('Read CSV File into DataFrame').fgetOrCreate()
from pyspark.sql.functions import col

df=spark.read.csv("/home/nirmala/Documents/precog_requirement_task/cases/cases/cases_2017.csv" ,header=True)
df2=pd.read_csv('/home/nirmala/2017_filtered.csv')

In [3]:
df_pending=df

df_pending = df_pending.drop(col("dist_code"))
df_pending = df_pending.drop(col("ddl_case_id"))
df_pending = df_pending.drop(col("court_no"))
df_pending = df_pending.drop(col("cino"))
df_pending = df_pending.drop(col("judge_position"))
df_pending = df_pending.drop(col("female_defendant"))
df_pending = df_pending.drop(col("female_petitioner"))
df_pending = df_pending.drop(col("female_adv_def"))
df_pending = df_pending.drop(col("female_adv_pet"))
df_pending = df_pending.drop(col("type_name"))
df_pending = df_pending.drop(col("purpose_name"))
df_pending = df_pending.drop(col("disp_name"))
df_pending = df_pending.drop(col("date_last_list"))
df_pending = df_pending.drop(col("date_first_list"))


df_pending

DataFrame[year: string, state_code: string, date_of_filing: string, date_of_decision: string, date_next_list: string]

In [4]:

df = df_pending.toPandas()

ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/home/nirmala/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nirmala/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nirmala/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving

In [5]:

df['date_of_filing'] = pd.to_datetime(df['date_of_filing'], format='%Y-%m-%d',errors = 'coerce') 


df['date_of_decision'] = pd.to_datetime(df['date_of_decision'], format='%Y-%m-%d',errors = 'coerce') 

df['date_next_list'] = pd.to_datetime(df['date_next_list'], format='%Y-%m-%d',errors = 'coerce')

In [6]:

# df['file_end'] =(df['date_next_list']-df['date_of_filing']).dt.year
df.info()

df['closing'] = df['date_next_list'].dt.year
df['filing'] = df['date_of_filing'].dt.year


df=df.drop(columns=['date_of_filing','date_of_decision','date_next_list'])

df['closing']=df['closing'].fillna('1900')


df['closing']=df['closing'].astype(int)
df['filing']=df['filing'].astype(int)

df

df.info()

df = df[~df['closing'].isin([2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022])]


df

df['pending_years']=df['closing']-df['filing']

df


df['filing'].unique()

df=df.drop(columns=['filing','closing'])

df=df.reset_index()

df=df.drop(columns=['index'])
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8552447 entries, 0 to 8552446
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   year              object
 1   state_code        object
 2   date_of_filing    datetime64[ns]
 3   date_of_decision  datetime64[ns]
 4   date_next_list    datetime64[ns]
dtypes: datetime64[ns](3), object(2)
memory usage: 326.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8552447 entries, 0 to 8552446
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   year        object
 1   state_code  object
 2   closing     int64
 3   filing      int64
dtypes: int64(2), object(2)
memory usage: 261.0+ MB

        year state_code  pending_years
0       2017         01           -117
1       2017         01           -117
2       2017         01           -117
3       2017         01           -117
4       2017         01           -117
...      ...        ...            ...
348275  2017         13           -117
348276  2017         13           -117
348277  2017         13           -117
348278  2017         13           -117
348279  2017         13           -117

[348280 rows x 3 columns]

In [7]:
df['state_code'].replace(to_replace='01', value="Maharashtra",inplace=True)
df['state_code'].replace(to_replace='02' ,value="Andhra Pradesh",inplace=True)
df['state_code'].replace(to_replace='03' ,value="Karnataka",inplace=True)
df['state_code'].replace(to_replace='04', value="Kerala",inplace=True)
df['state_code'].replace(to_replace='05' ,value="Himachal Pradesh",inplace=True)
df['state_code'].replace(to_replace='06', value="Assam",inplace=True)
df['state_code'].replace(to_replace='07', value="Jharkhand",inplace=True)
df['state_code'].replace(to_replace='08' ,value="Bihar",inplace=True)
df['state_code'].replace(to_replace='09' ,value="Rajasthan",inplace=True)
df['state_code'].replace(to_replace='10' ,value="Tamilnadu",inplace=True)
df['state_code'].replace(to_replace='11',value="Orissa",inplace=True)
df['state_code'].replace(to_replace='12' ,value="Jammu and kashmir",inplace=True)
df['state_code'].replace(to_replace='13' ,value="Uttar pradesh",inplace=True)
df['state_code'].replace(to_replace='14' ,value="Haryana",inplace=True)
df['state_code'].replace(to_replace='15' ,value="Uttarakhand",inplace=True)
df['state_code'].replace(to_replace='16' ,value="West Bengal",inplace=True)
df['state_code'].replace(to_replace='17' ,value="Gujarath",inplace=True)
df['state_code'].replace(to_replace='18' ,value="Chattisgarh",inplace=True)
df['state_code'].replace(to_replace='19' ,value="Mizoram",inplace=True)
df['state_code'].replace(to_replace='20' ,value="Tripura",inplace=True)
df['state_code'].replace(to_replace='21' ,value="Meghalaya",inplace=True)
df['state_code'].replace(to_replace='22' ,value="Punjab",inplace=True)
df['state_code'].replace(to_replace='23' ,value="Madhya Pradesh",inplace=True)
df['state_code'].replace(to_replace='24' , value="Sikkim",inplace=True)
df['state_code'].replace(to_replace='25' ,value="Manipur",inplace=True)
df['state_code'].replace(to_replace='26' ,value="Delhi",inplace=True)
df['state_code'].replace(to_replace='27' ,value="Chandigarh",inplace=True)
df['state_code'].replace(to_replace='29' ,value="Telangana",inplace=True)
df['state_code'].replace(to_replace='30' ,value="Goa",inplace=True)
df['state_code'].replace(to_replace='31' ,value="Diu and daman",inplace=True)
df['state_code'].replace(to_replace='32',value="DNH at silvasa",inplace=True)
df['state_code'].replace(to_replace='33' ,value="Ladakh",inplace=True)

df

        year     state_code  pending_years
0       2017    Maharashtra           -117
1       2017    Maharashtra           -117
2       2017    Maharashtra           -117
3       2017    Maharashtra           -117
4       2017    Maharashtra           -117
...      ...            ...            ...
348275  2017  Uttar pradesh           -117
348276  2017  Uttar pradesh           -117
348277  2017  Uttar pradesh           -117
348278  2017  Uttar pradesh           -117
348279  2017  Uttar pradesh           -117

[348280 rows x 3 columns]

In [14]:
del df_pending

In [15]:


df_pending = df["state_code"].value_counts().reset_index()


df_pending

df_pending['state_code']=df_pending['state_code'].sort_values()
df_pending.rename(columns={"index": "state", "state_code": "pendingcases_count"}, inplace=True)
new_rows_pending = pd.DataFrame({'state' : ['Chandigarh','Chattisgarh','DNH at silvasa','Delhi','Diu and daman','Goa','Gujarath','Haryana','Ladakh','Madhya Pradesh','Manipur','Meghalaya','Mizoram','Punjab','Sikkim','Telangana','Tripura','Uttarakhand','West Bengal'], 'pendingcases_count' : [ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]})
df_pending= pd.concat([new_rows_pending, df_pending], ignore_index=True)
df_pending

df_pending['pending_casesperlakh']=df_pending['pendingcases_count']/100000
df_pending.insert(3, 'Year', 2017)

df_pending

                state  pendingcases_count  pending_casesperlakh  Year
0          Chandigarh                   0               0.00000  2017
1         Chattisgarh                   0               0.00000  2017
2      DNH at silvasa                   0               0.00000  2017
3               Delhi                   0               0.00000  2017
4       Diu and daman                   0               0.00000  2017
5                 Goa                   0               0.00000  2017
6            Gujarath                   0               0.00000  2017
7             Haryana                   0               0.00000  2017
8              Ladakh                   0               0.00000  2017
9      Madhya Pradesh                   0               0.00000  2017
10            Manipur                   0               0.00000  2017
11          Meghalaya                   0               0.00000  2017
12            Mizoram                   0               0.00000  2017
13             Punjab                   0               0.00000  2017
14             Sikkim                   0               0.00000  2017
15          Telangana                   0               0.00000  2017
16            Tripura                   0               0.00000  2017
17        Uttarakhand                   0               0.00000  2017
18        West Bengal                   0               0.00000  2017
19          Rajasthan              127745               1.27745  2017
20      Uttar pradesh               62466               0.62466  2017
21          Karnataka               57574               0.57574  2017
22          Tamilnadu               40631               0.40631  2017
23        Maharashtra               27996               0.27996  2017
24             Orissa               10287               0.10287  2017
25   Himachal Pradesh                6589               0.06589  2017
26              Bihar                6501               0.06501  2017
27              Assam                3002               0.03002  2017
28             Kerala                1723               0.01723  2017
29     Andhra Pradesh                1656               0.01656  2017
30          Jharkhand                1195               0.01195  2017
31  Jammu and kashmir                 915               0.00915  2017

In [16]:
df_pending=df_pending.sort_values(by='state')
df_pending=df_pending.reset_index()
df_pending=df_pending.drop(columns=['index'])  

df_pending

                state  pendingcases_count  pending_casesperlakh  Year
0      Andhra Pradesh                1656               0.01656  2017
1               Assam                3002               0.03002  2017
2               Bihar                6501               0.06501  2017
3          Chandigarh                   0               0.00000  2017
4         Chattisgarh                   0               0.00000  2017
5      DNH at silvasa                   0               0.00000  2017
6               Delhi                   0               0.00000  2017
7       Diu and daman                   0               0.00000  2017
8                 Goa                   0               0.00000  2017
9            Gujarath                   0               0.00000  2017
10            Haryana                   0               0.00000  2017
11   Himachal Pradesh                6589               0.06589  2017
12  Jammu and kashmir                 915               0.00915  2017
13          Jharkhand                1195               0.01195  2017
14          Karnataka               57574               0.57574  2017
15             Kerala                1723               0.01723  2017
16             Ladakh                   0               0.00000  2017
17     Madhya Pradesh                   0               0.00000  2017
18        Maharashtra               27996               0.27996  2017
19            Manipur                   0               0.00000  2017
20          Meghalaya                   0               0.00000  2017
21            Mizoram                   0               0.00000  2017
22             Orissa               10287               0.10287  2017
23             Punjab                   0               0.00000  2017
24          Rajasthan              127745               1.27745  2017
25             Sikkim                   0               0.00000  2017
26          Tamilnadu               40631               0.40631  2017
27          Telangana                   0               0.00000  2017
28            Tripura                   0               0.00000  2017
29      Uttar pradesh               62466               0.62466  2017
30        Uttarakhand                   0               0.00000  2017
31        West Bengal                   0               0.00000  2017

In [17]:

df_merged=pd.merge(df2,df_pending,on='state')
df_merged

,year,state,dismissed_count,prison_count,withdrawal_count,avg_decision_end_per1lakhcases,avg_fileend_per1lakhcases,avg_filecourt_per1lakhcases,criminal_count,criminal_perlakh,noncriminal_count,noncriminal_perlakh,pendingcases_count,pending_casesperlakh,Year
0,2017,Andhra Pradesh,0,0,0,0,310,60,79525,0.79525,45845,0.45845,1656,0.01656,2017
1,2017,Assam,0,566,0,0,339,68,52800,0.52800,36124,0.36124,3002,0.03002,2017
2,2017,Bihar,9,2,857,6,241,63,54902,0.54902,132444,1.32444,6501,0.06501,2017
3,2017,Chandigarh,2,2,39,0,2903,19,10583,0.10583,1063,0.01063,0,0.00000,2017
4,2017,Chattisgarh,93,189,42,0,477,47,42355,0.42355,24785,0.24785,0,0.00000,2017
5,2017,DNH at silvasa,0,2,0,0,95954,4190,149,0.00149,173,0.00173,0,0.00000,2017
6,2017,Delhi,11,833,5034,0,256,21,97030,0.97030,38537,0.38537,0,0.00000,2017
7,2017,Diu and daman,0,0,0,0,24610,2509,385,0.00385,229,0.00229,0,0.00000,2017
8,2017,Goa,0,0,0,0,2104,194,9178,0.09178,2371,0.02371,0,0.00000,2017
9,2017,Gujarath,0,33884,0,0,101,10,185540,1.85540,88104,0.88104,0,0.00000,2017
10,2017,Haryana,65,0,4149,0,131,9,173864,1.73864,54964,0.54964,0,0.00000,2017
11,2017,Himachal Pradesh,0,0,0,0,575,68,41616,0.41616,14784,0.14784,6589,0.06589,2017
12,2017,Jammu and kashmir,5,3,5,0,1562,478,23208,0.23208,7365,0.07365,915,0.00915,2017
13,2017,Jharkhand,16,1342,113,1,468,47,20621,0.20621,47497,0.47497,1195,0.01195,2017
14,2017,Karnataka,32,31053,0,1,67,7,298348,2.98348,125317,1.25317,57574,0.57574,2017
15,2017,Kerala,6,11728,1,0,123,27,181271,1.81271,134457,1.34457,1723,0.01723,2017
16,2017,Ladakh,0,0,0,0,305769,66220,95,0.00095,27,0.00027,0,0.00000,2017
17,2017,Madhya Pradesh,0,0,0,0,114,11,157515,1.57515,131364,1.31364,0,0.00000,2017
18,2017,Maharashtra,36,6998,0,0,78,5,356258,3.56258,151728,1.51728,27996,0.27996,2017
19,2017,Manipur,0,3,0,5,2399,205,2982,0.02982,2492,0.02492,0,0.00000,2017
20,2017,Meghalaya,0,5,1,6,6278,82,2204,0.02204,485,0.00485,0,0.00000,2017
21,2017,Mizoram,0,0,0,0,46289,12556,463,0.00463,206,0.00206,0,0.00000,2017
22,2017,Orissa,7,159,40,4,547,79,69388,0.69388,46615,0.46615,10287,0.10287,2017
23,2017,Punjab,0,0,982,0,148,5,141987,1.41987,55161,0.55161,0,0.00000,2017
24,2017,Rajasthan,129,8047,10,0,110,15,204990,2.04990,147316,1.47316,127745,1.27745,2017
25,2017,Sikkim,2,24,0,0,7315,452,905,0.00905,745,0.00745,0,0.00000,2017
26,2017,Tamilnadu,0,0,0,0,149,21,175175,1.75175,81654,0.81654,40631,0.40631,2017
27,2017,Telangana,0,0,0,0,544,150,42992,0.42992,40997,0.40997,0,0.00000,2017
28,2017,Tripura,1,26,0,7,7900,666,2380,0.02380,2064,0.02064,0,0.00000,2017
29,2017,Uttar pradesh,127,33,1150,0,35,5,590719,5.90719,392831,3.92831,62466,0.62466,2017
30,2017,Uttarakhand,0,405,0,0,807,95,39058,0.39058,6570,0.06570,0,0.00000,2017
31,2017,West Bengal,1,3652,0,0,280,36,91193,0.91193,84525,0.84525,0,0.00000,2017

In [18]:
df_merged=df_merged.drop(columns=['Year'])

# df_merged.to_csv('2014_filtered.csv', index=False)


df_merged=df_merged.reindex(columns=['year','state','dismissed_count','prison_count','withdrawal_count','avg_decision_end_per1lakhcases','avg_fileend_per1lakhcases','avg_filecourt_per1lakhcases','pendingcases_count','pending_casesperlakh','criminal_count','criminal_perlakh','noncriminal_count','noncriminal_perlakh'])
df_merged.to_csv('2017_filtered.csv', index=False)
df_merged

,year,state,dismissed_count,prison_count,withdrawal_count,avg_decision_end_per1lakhcases,avg_fileend_per1lakhcases,avg_filecourt_per1lakhcases,pendingcases_count,pending_casesperlakh,criminal_count,criminal_perlakh,noncriminal_count,noncriminal_perlakh
0,2017,Andhra Pradesh,0,0,0,0,310,60,1656,0.01656,79525,0.79525,45845,0.45845
1,2017,Assam,0,566,0,0,339,68,3002,0.03002,52800,0.52800,36124,0.36124
2,2017,Bihar,9,2,857,6,241,63,6501,0.06501,54902,0.54902,132444,1.32444
3,2017,Chandigarh,2,2,39,0,2903,19,0,0.00000,10583,0.10583,1063,0.01063
4,2017,Chattisgarh,93,189,42,0,477,47,0,0.00000,42355,0.42355,24785,0.24785
5,2017,DNH at silvasa,0,2,0,0,95954,4190,0,0.00000,149,0.00149,173,0.00173
6,2017,Delhi,11,833,5034,0,256,21,0,0.00000,97030,0.97030,38537,0.38537
7,2017,Diu and daman,0,0,0,0,24610,2509,0,0.00000,385,0.00385,229,0.00229
8,2017,Goa,0,0,0,0,2104,194,0,0.00000,9178,0.09178,2371,0.02371
9,2017,Gujarath,0,33884,0,0,101,10,0,0.00000,185540,1.85540,88104,0.88104
10,2017,Haryana,65,0,4149,0,131,9,0,0.00000,173864,1.73864,54964,0.54964
11,2017,Himachal Pradesh,0,0,0,0,575,68,6589,0.06589,41616,0.41616,14784,0.14784
12,2017,Jammu and kashmir,5,3,5,0,1562,478,915,0.00915,23208,0.23208,7365,0.07365
13,2017,Jharkhand,16,1342,113,1,468,47,1195,0.01195,20621,0.20621,47497,0.47497
14,2017,Karnataka,32,31053,0,1,67,7,57574,0.57574,298348,2.98348,125317,1.25317
15,2017,Kerala,6,11728,1,0,123,27,1723,0.01723,181271,1.81271,134457,1.34457
16,2017,Ladakh,0,0,0,0,305769,66220,0,0.00000,95,0.00095,27,0.00027
17,2017,Madhya Pradesh,0,0,0,0,114,11,0,0.00000,157515,1.57515,131364,1.31364
18,2017,Maharashtra,36,6998,0,0,78,5,27996,0.27996,356258,3.56258,151728,1.51728
19,2017,Manipur,0,3,0,5,2399,205,0,0.00000,2982,0.02982,2492,0.02492
20,2017,Meghalaya,0,5,1,6,6278,82,0,0.00000,2204,0.02204,485,0.00485
21,2017,Mizoram,0,0,0,0,46289,12556,0,0.00000,463,0.00463,206,0.00206
22,2017,Orissa,7,159,40,4,547,79,10287,0.10287,69388,0.69388,46615,0.46615
23,2017,Punjab,0,0,982,0,148,5,0,0.00000,141987,1.41987,55161,0.55161
24,2017,Rajasthan,129,8047,10,0,110,15,127745,1.27745,204990,2.04990,147316,1.47316
25,2017,Sikkim,2,24,0,0,7315,452,0,0.00000,905,0.00905,745,0.00745
26,2017,Tamilnadu,0,0,0,0,149,21,40631,0.40631,175175,1.75175,81654,0.81654
27,2017,Telangana,0,0,0,0,544,150,0,0.00000,42992,0.42992,40997,0.40997
28,2017,Tripura,1,26,0,7,7900,666,0,0.00000,2380,0.02380,2064,0.02064
29,2017,Uttar pradesh,127,33,1150,0,35,5,62466,0.62466,590719,5.90719,392831,3.92831
30,2017,Uttarakhand,0,405,0,0,807,95,0,0.00000,39058,0.39058,6570,0.06570
31,2017,West Bengal,1,3652,0,0,280,36,0,0.00000,91193,0.91193,84525,0.84525