In [1]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
import pandas as pd
spark = SparkSession.builder \
    .appName('Read CSV File into DataFrame') \
    .config('spark.executor.memory', '10g') \
    .config('spark.driver.memory', '50g') \
    .getOrCreate()
# spark = SparkSession.builder.appName('Read CSV File into DataFrame').getOrCreate()
from pyspark.sql.functions import col

df=spark.read.csv("/home/nirmala/Documents/precog_requirement_task/cases/cases/cases_2013.csv" ,header=True)
df2=pd.read_csv('/home/nirmala/2013_filtered.csv')

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

23/01/10 10:18:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [2]:
df_pending=df

df_pending = df_pending.drop(col("dist_code"))
df_pending = df_pending.drop(col("ddl_case_id"))
df_pending = df_pending.drop(col("court_no"))
df_pending = df_pending.drop(col("cino"))
df_pending = df_pending.drop(col("judge_position"))
df_pending = df_pending.drop(col("female_defendant"))
df_pending = df_pending.drop(col("female_petitioner"))
df_pending = df_pending.drop(col("female_adv_def"))
df_pending = df_pending.drop(col("female_adv_pet"))
df_pending = df_pending.drop(col("type_name"))
df_pending = df_pending.drop(col("purpose_name"))
df_pending = df_pending.drop(col("disp_name"))
df_pending = df_pending.drop(col("date_last_list"))
df_pending = df_pending.drop(col("date_first_list"))

In [3]:
df_pending
del df
df = df_pending.toPandas()

In [4]:
df['date_of_filing'] = pd.to_datetime(df['date_of_filing'], format='%Y-%m-%d',errors = 'coerce') 


df['date_of_decision'] = pd.to_datetime(df['date_of_decision'], format='%Y-%m-%d',errors = 'coerce') 

df['date_next_list'] = pd.to_datetime(df['date_next_list'], format='%Y-%m-%d',errors = 'coerce') 



# df['file_end'] =(df['date_next_list']-df['date_of_filing']).dt.year
df.info()

df['closing'] = df['date_next_list'].dt.year
df['filing'] = df['date_of_filing'].dt.year

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7555617 entries, 0 to 7555616
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   year              object
 1   state_code        object
 2   date_of_filing    datetime64[ns]
 3   date_of_decision  datetime64[ns]
 4   date_next_list    datetime64[ns]
dtypes: datetime64[ns](3), object(2)
memory usage: 288.2+ MB

In [5]:
df=df.drop(columns=['date_of_filing','date_of_decision','date_next_list'])

df['closing']=df['closing'].fillna('1900')


df['closing']=df['closing'].astype(int)
df['filing']=df['filing'].astype(int)

df

df.info()

df = df[~df['closing'].isin([2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022])]


df

df['pending_years']=df['closing']-df['filing']

df


df['filing'].unique()

df=df.drop(columns=['filing','closing'])

df=df.reset_index()

df=df.drop(columns=['index'])
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7555617 entries, 0 to 7555616
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   year        object
 1   state_code  object
 2   closing     int64
 3   filing      int64
dtypes: int64(2), object(2)
memory usage: 230.6+ MB

        year state_code  pending_years
0       2013         01           -113
1       2013         01           -113
2       2013         01           -113
3       2013         01           -113
4       2013         01           -113
...      ...        ...            ...
117060  2013         31           -113
117061  2013         31           -113
117062  2013         31           -113
117063  2013         31           -113
117064  2013         31           -113

[117065 rows x 3 columns]

In [6]:

df['state_code'].replace(to_replace='01', value="Maharashtra",inplace=True)
df['state_code'].replace(to_replace='02' ,value="Andhra Pradesh",inplace=True)
df['state_code'].replace(to_replace='03' ,value="Karnataka",inplace=True)
df['state_code'].replace(to_replace='04', value="Kerala",inplace=True)
df['state_code'].replace(to_replace='05' ,value="Himachal Pradesh",inplace=True)
df['state_code'].replace(to_replace='06', value="Assam",inplace=True)
df['state_code'].replace(to_replace='07', value="Jharkhand",inplace=True)
df['state_code'].replace(to_replace='08' ,value="Bihar",inplace=True)
df['state_code'].replace(to_replace='09' ,value="Rajasthan",inplace=True)
df['state_code'].replace(to_replace='10' ,value="Tamilnadu",inplace=True)
df['state_code'].replace(to_replace='11',value="Orissa",inplace=True)
df['state_code'].replace(to_replace='12' ,value="Jammu and kashmir",inplace=True)
df['state_code'].replace(to_replace='13' ,value="Uttar pradesh",inplace=True)
df['state_code'].replace(to_replace='14' ,value="Haryana",inplace=True)
df['state_code'].replace(to_replace='15' ,value="Uttarakhand",inplace=True)
df['state_code'].replace(to_replace='16' ,value="West Bengal",inplace=True)
df['state_code'].replace(to_replace='17' ,value="Gujarath",inplace=True)
df['state_code'].replace(to_replace='18' ,value="Chattisgarh",inplace=True)
df['state_code'].replace(to_replace='19' ,value="Mizoram",inplace=True)
df['state_code'].replace(to_replace='20' ,value="Tripura",inplace=True)
df['state_code'].replace(to_replace='21' ,value="Meghalaya",inplace=True)
df['state_code'].replace(to_replace='22' ,value="Punjab",inplace=True)
df['state_code'].replace(to_replace='23' ,value="Madhya Pradesh",inplace=True)
df['state_code'].replace(to_replace='24' , value="Sikkim",inplace=True)
df['state_code'].replace(to_replace='25' ,value="Manipur",inplace=True)
df['state_code'].replace(to_replace='26' ,value="Delhi",inplace=True)
df['state_code'].replace(to_replace='27' ,value="Chandigarh",inplace=True)
df['state_code'].replace(to_replace='29' ,value="Telangana",inplace=True)
df['state_code'].replace(to_replace='30' ,value="Goa",inplace=True)
df['state_code'].replace(to_replace='31' ,value="Diu and daman",inplace=True)
df['state_code'].replace(to_replace='32',value="DNH at silvasa",inplace=True)
df['state_code'].replace(to_replace='33' ,value="Ladakh",inplace=True)
df

df_pending = df["state_code"].value_counts().reset_index()


df_pending

df_pending['state_code']=df_pending['state_code'].sort_values()
df_pending.rename(columns={"index": "state", "state_code": "pendingcases_count"}, inplace=True)
new_rows_pending = pd.DataFrame({'state' : [ 'DNH at silvasa','Ladakh','Mizoram','Meghalaya'], 'pendingcases_count' : [ 0,0,0,0]})
df_pending= pd.concat([new_rows_pending, df_pending], ignore_index=True)
df_pending

df_pending['pending_casesperlakh']=df_pending['pendingcases_count']/100000
df_pending.insert(3, 'Year', 2013)

df_pending

                state  pendingcases_count  pending_casesperlakh  Year
0      Madhya Pradesh               38520               0.38520  2013
1           Karnataka               37618               0.37618  2013
2         West Bengal                7668               0.07668  2013
3            Gujarath                6066               0.06066  2013
4         Maharashtra                5459               0.05459  2013
5                 Goa                5448               0.05448  2013
6       Uttar pradesh                4147               0.04147  2013
7              Kerala                2471               0.02471  2013
8               Bihar                2230               0.02230  2013
9               Assam                1164               0.01164  2013
10     Andhra Pradesh                1004               0.01004  2013
11          Tamilnadu                 805               0.00805  2013
12        Chattisgarh                 789               0.00789  2013
13             Orissa                 771               0.00771  2013
14          Telangana                 579               0.00579  2013
15          Jharkhand                 577               0.00577  2013
16              Delhi                 543               0.00543  2013
17          Rajasthan                 283               0.00283  2013
18             Punjab                 270               0.00270  2013
19            Haryana                 252               0.00252  2013
20      Diu and daman                 129               0.00129  2013
21   Himachal Pradesh                  98               0.00098  2013
22        Uttarakhand                  92               0.00092  2013
23  Jammu and kashmir                  63               0.00063  2013
24            Manipur                  10               0.00010  2013
25            Tripura                   7               0.00007  2013
26             Sikkim                   1               0.00001  2013
27         Chandigarh                   1               0.00001  2013

In [7]:
df_pending=df_pending.sort_values(by='state')
df_pending=df_pending.reset_index()
df_pending=df_pending.drop(columns=['index'])

In [8]:
df_merged=pd.merge(df2,df_pending,on='state')
df_merged

,year,state,dismissed_count,prison_count,withdrawal_count,avg_decision_end_per1lakhcases,avg_fileend_per1lakhcases,avg_filecourt_per1lakhcases,criminal_count,criminal_perlakh,noncriminal_count,noncriminal_perlakh,pendingcases_count,pending_casesperlakh,Year
0,2013,Andhra Pradesh,36882,0,2653,0,411,90,123547,1.23547,83755,0.83755,1004,0.01004,2013
1,2013,Assam,13227,553,1744,0,603,179,72041,0.72041,90908,0.90908,1164,0.01164,2013
2,2013,Bihar,34561,3,3002,5,518,215,119772,1.19772,243717,2.43717,2230,0.02230,2013
3,2013,Chandigarh,4476,0,4683,16,2020,328,23703,0.23703,19422,0.19422,1,0.00001,2013
4,2013,Chattisgarh,6304,0,1132,1,1912,777,34027,0.34027,32236,0.32236,789,0.00789,2013
5,2013,Delhi,19709,2,22472,10,523,58,127004,1.27004,91663,0.91663,543,0.00543,2013
6,2013,Diu and daman,33,0,46,0,25849,1928,1091,0.01091,392,0.00392,129,0.00129,2013
7,2013,Goa,18,0,93,64,2029,367,25937,0.25937,21699,0.21699,5448,0.05448,2013
8,2013,Gujarath,27380,0,37745,0,116,27,415864,4.15864,236419,2.36419,6066,0.06066,2013
9,2013,Haryana,53250,69,47060,1,205,35,254230,2.54230,191935,1.91935,252,0.00252,2013
10,2013,Himachal Pradesh,9915,0,6930,3,1203,265,66075,0.66075,62443,0.62443,98,0.00098,2013
11,2013,Jammu and kashmir,2925,0,532,10,4108,2397,27152,0.27152,18455,0.18455,63,0.00063,2013
12,2013,Jharkhand,10673,9,1921,2,1250,437,57275,0.57275,77039,0.77039,577,0.00577,2013
13,2013,Karnataka,104421,3,6668,0,59,6,754092,7.54092,480528,4.80528,37618,0.37618,2013
14,2013,Kerala,49062,0,3423,0,179,50,306381,3.06381,162347,1.62347,2471,0.02471,2013
15,2013,Madhya Pradesh,61384,0,11422,2,143,32,406424,4.06424,397560,3.97560,38520,0.38520,2013
16,2013,Maharashtra,59404,17,30938,0,80,5,723711,7.23711,479884,4.79884,5459,0.05459,2013
17,2013,Manipur,679,0,64,8,12336,2920,4277,0.04277,2942,0.02942,10,0.00010,2013
18,2013,Orissa,9300,0,14829,5,875,313,124949,1.24949,118377,1.18377,771,0.00771,2013
19,2013,Punjab,79752,73,54689,0,177,21,282100,2.82100,226416,2.26416,270,0.00270,2013
20,2013,Rajasthan,21428,14,15145,0,205,43,400004,4.00004,375846,3.75846,283,0.00283,2013
21,2013,Sikkim,43,0,356,11,3454,492,2942,0.02942,3019,0.03019,1,0.00001,2013
22,2013,Tamilnadu,87127,0,2935,0,285,62,300431,3.00431,235529,2.35529,805,0.00805,2013
23,2013,Telangana,30405,0,1509,0,493,123,98356,0.98356,91551,0.91551,579,0.00579,2013
24,2013,Tripura,802,0,108,3,5433,875,8244,0.08244,10653,0.10653,7,0.00007,2013
25,2013,Uttar pradesh,106043,0,2433,4,114,32,887087,8.87087,838897,8.38897,4147,0.04147,2013
26,2013,Uttarakhand,13672,0,566,9,671,113,79320,0.79320,27611,0.27611,92,0.00092,2013
27,2013,West Bengal,41932,0,1198,1,456,186,206383,2.06383,203925,2.03925,7668,0.07668,2013

In [9]:
df_merged=df_merged.drop(columns=['Year'])

In [11]:
df_merged.to_csv('2013_filtered.csv', index=False)

In [10]:
df_merged=df_merged.reindex(columns=['year','state','dismissed_count','prison_count','withdrawal_count','avg_decision_end_per1lakhcases','avg_fileend_per1lakhcases','avg_filecourt_per1lakhcases','pendingcases_count','pending_casesperlakh','criminal_count','criminal_perlakh','noncriminal_count','noncriminal_perlakh'])

In [8]:
df_merged.to_csv('2013_filtered.csv', index=False)

In [12]:
df_merged

,year,state,dismissed_count,prison_count,withdrawal_count,avg_decision_end_per1lakhcases,avg_fileend_per1lakhcases,avg_filecourt_per1lakhcases,pendingcases_count,pending_casesperlakh,criminal_count,criminal_perlakh,noncriminal_count,noncriminal_perlakh
0,2013,Andhra Pradesh,36882,0,2653,0,411,90,1004,0.01004,123547,1.23547,83755,0.83755
1,2013,Assam,13227,553,1744,0,603,179,1164,0.01164,72041,0.72041,90908,0.90908
2,2013,Bihar,34561,3,3002,5,518,215,2230,0.02230,119772,1.19772,243717,2.43717
3,2013,Chandigarh,4476,0,4683,16,2020,328,1,0.00001,23703,0.23703,19422,0.19422
4,2013,Chattisgarh,6304,0,1132,1,1912,777,789,0.00789,34027,0.34027,32236,0.32236
5,2013,Delhi,19709,2,22472,10,523,58,543,0.00543,127004,1.27004,91663,0.91663
6,2013,Diu and daman,33,0,46,0,25849,1928,129,0.00129,1091,0.01091,392,0.00392
7,2013,Goa,18,0,93,64,2029,367,5448,0.05448,25937,0.25937,21699,0.21699
8,2013,Gujarath,27380,0,37745,0,116,27,6066,0.06066,415864,4.15864,236419,2.36419
9,2013,Haryana,53250,69,47060,1,205,35,252,0.00252,254230,2.54230,191935,1.91935
10,2013,Himachal Pradesh,9915,0,6930,3,1203,265,98,0.00098,66075,0.66075,62443,0.62443
11,2013,Jammu and kashmir,2925,0,532,10,4108,2397,63,0.00063,27152,0.27152,18455,0.18455
12,2013,Jharkhand,10673,9,1921,2,1250,437,577,0.00577,57275,0.57275,77039,0.77039
13,2013,Karnataka,104421,3,6668,0,59,6,37618,0.37618,754092,7.54092,480528,4.80528
14,2013,Kerala,49062,0,3423,0,179,50,2471,0.02471,306381,3.06381,162347,1.62347
15,2013,Madhya Pradesh,61384,0,11422,2,143,32,38520,0.38520,406424,4.06424,397560,3.97560
16,2013,Maharashtra,59404,17,30938,0,80,5,5459,0.05459,723711,7.23711,479884,4.79884
17,2013,Manipur,679,0,64,8,12336,2920,10,0.00010,4277,0.04277,2942,0.02942
18,2013,Orissa,9300,0,14829,5,875,313,771,0.00771,124949,1.24949,118377,1.18377
19,2013,Punjab,79752,73,54689,0,177,21,270,0.00270,282100,2.82100,226416,2.26416
20,2013,Rajasthan,21428,14,15145,0,205,43,283,0.00283,400004,4.00004,375846,3.75846
21,2013,Sikkim,43,0,356,11,3454,492,1,0.00001,2942,0.02942,3019,0.03019
22,2013,Tamilnadu,87127,0,2935,0,285,62,805,0.00805,300431,3.00431,235529,2.35529
23,2013,Telangana,30405,0,1509,0,493,123,579,0.00579,98356,0.98356,91551,0.91551
24,2013,Tripura,802,0,108,3,5433,875,7,0.00007,8244,0.08244,10653,0.10653
25,2013,Uttar pradesh,106043,0,2433,4,114,32,4147,0.04147,887087,8.87087,838897,8.38897
26,2013,Uttarakhand,13672,0,566,9,671,113,92,0.00092,79320,0.79320,27611,0.27611
27,2013,West Bengal,41932,0,1198,1,456,186,7668,0.07668,206383,2.06383,203925,2.03925